// math_native.cpp -- Native Math subject library.
//
// Synthesizes the __NativeMath class: constants (pi, e, tau) and executable
// numeric functions (abs, sign, min, max, clamp, sqrt, exp, log, pow, sin,
// cos, tan, hypot, fmod) built from ordinary Sleela Core methods. Math is the
// foundational numeric domain; physics and economics depend on it.
#include "native_add.h"
#include "native_builders.h"

namespace sleela { namespace native {
using namespace sleela::native::builders;

void addMath(Program&p){ClassDecl c;c.name="__NativeMath";auto m=M0("double","__native_math_pi");m.body->stmts.push_back(Ret(D(3.14159265358979323846)));c.methods.push_back(std::move(m));m=M0("double","__native_math_e");m.body->stmts.push_back(Ret(D(2.71828182845904523536)));c.methods.push_back(std::move(m));m=M0("double","__native_math_tau");m.body->stmts.push_back(Ret(D(6.28318530717958647692)));c.methods.push_back(std::move(m));m=M1("double","__native_math_abs","double","x");{auto i=std::make_unique<IfStmt>();i->cond=Bn("<",V("x"),D(0));i->thenS=Ret(Neg(V("x")));i->elseS=Ret(V("x"));m.body->stmts.push_back(std::move(i));}c.methods.push_back(std::move(m));m=M1("double","__native_math_sign","double","x");{auto i=std::make_unique<IfStmt>();i->cond=Bn(">",V("x"),D(0));i->thenS=Ret(D(1));auto j=std::make_unique<IfStmt>();j->cond=Bn("<",V("x"),D(0));j->thenS=Ret(D(-1));j->elseS=Ret(D(0));i->elseS=std::move(j);m.body->stmts.push_back(std::move(i));}c.methods.push_back(std::move(m));m=M2("double","__native_math_min","double","a","double","b");{auto i=std::make_unique<IfStmt>();i->cond=Bn("<",V("a"),V("b"));i->thenS=Ret(V("a"));i->elseS=Ret(V("b"));m.body->stmts.push_back(std::move(i));}c.methods.push_back(std::move(m));m=M2("double","__native_math_max","double","a","double","b");{auto i=std::make_unique<IfStmt>();i->cond=Bn(">",V("a"),V("b"));i->thenS=Ret(V("a"));i->elseS=Ret(V("b"));m.body->stmts.push_back(std::move(i));}c.methods.push_back(std::move(m));m=M3("double","__native_math_clamp","double","x","double","lo","double","hi");m.body->stmts.push_back(Ret(C2("__native_math_min",C2("__native_math_max",V("x"),V("lo")),V("hi"))));c.methods.push_back(std::move(m));m=M1("double","__native_math_sqrt","double","x");
{
  // Range-reduced Newton sqrt: robust for any magnitude. Reduce x into
  // [0.25,4) by factoring out powers of 4 (each divide-by-4 halves the root),
  // run Newton there, then scale the root back. Non-positive x returns 0.
  {auto guard=std::make_unique<IfStmt>();guard->cond=Bn("<=",V("x"),D(0));guard->thenS=Ret(D(0));m.body->stmts.push_back(std::move(guard));}
  m.body->stmts.push_back(Decl("double","s",D(1)));
  {auto b=std::make_unique<Block>();b->stmts.push_back(Set("x",Bn("/",V("x"),D(4))));b->stmts.push_back(Set("s",Bn("*",V("s"),D(2))));m.body->stmts.push_back(Loop(Bn(">=",V("x"),D(4)),std::move(b)));}
  {auto b=std::make_unique<Block>();b->stmts.push_back(Set("x",Bn("*",V("x"),D(4))));b->stmts.push_back(Set("s",Bn("/",V("s"),D(2))));m.body->stmts.push_back(Loop(Bn("<",V("x"),D(0.25)),std::move(b)));}
  m.body->stmts.push_back(Decl("double","g",Bn("+",V("x"),D(0.5))));
  m.body->stmts.push_back(Decl("int","i",I(0)));
  {auto b=std::make_unique<Block>();b->stmts.push_back(Set("g",Bn("/",Bn("+",V("g"),Bn("/",V("x"),V("g"))),D(2))));b->stmts.push_back(Set("i",Bn("+",V("i"),I(1))));m.body->stmts.push_back(Loop(Bn("<",V("i"),I(20)),std::move(b)));}
  m.body->stmts.push_back(Ret(Bn("*",V("g"),V("s"))));
}
c.methods.push_back(std::move(m));m=M1("double","__native_math_exp","double","x");m.body->stmts.push_back(Decl("double","term",D(1)));m.body->stmts.push_back(Decl("double","sum",D(1)));m.body->stmts.push_back(Decl("int","i",I(1)));{auto b=std::make_unique<Block>();b->stmts.push_back(Set("term",Bn("/",Bn("*",V("term"),V("x")),V("i"))));b->stmts.push_back(Set("sum",Bn("+",V("sum"),V("term"))));b->stmts.push_back(Set("i",Bn("+",V("i"),I(1))));m.body->stmts.push_back(Loop(Bn("<",V("i"),I(30)),std::move(b)));}m.body->stmts.push_back(Ret(V("sum")));c.methods.push_back(std::move(m));m=M1("double","__native_math_log","double","x");m.body->stmts.push_back(Decl("double","z",Bn("/",Bn("-",V("x"),D(1)),Bn("+",V("x"),D(1)))));m.body->stmts.push_back(Decl("double","z2",Bn("*",V("z"),V("z"))));m.body->stmts.push_back(Decl("double","term",V("z")));m.body->stmts.push_back(Decl("double","sum",V("z")));m.body->stmts.push_back(Decl("int","i",I(1)));{auto b=std::make_unique<Block>();b->stmts.push_back(Set("term",Bn("*",V("term"),V("z2"))));b->stmts.push_back(Set("sum",Bn("+",V("sum"),Bn("/",V("term"),Bn("+",Bn("*",I(2),V("i")),I(1))))));b->stmts.push_back(Set("i",Bn("+",V("i"),I(1))));m.body->stmts.push_back(Loop(Bn("<",V("i"),I(24)),std::move(b)));}m.body->stmts.push_back(Ret(Bn("*",D(2),V("sum"))));c.methods.push_back(std::move(m));m=M2("double","__native_math_pow","double","x","double","y");m.body->stmts.push_back(Ret(C1("__native_math_exp",Bn("*",V("y"),C1("__native_math_log",V("x"))))));c.methods.push_back(std::move(m));m=M1("double","__native_math_sin","double","x");m.body->stmts.push_back(Decl("double","term",V("x")));m.body->stmts.push_back(Decl("double","sum",V("x")));m.body->stmts.push_back(Decl("double","xx",Bn("*",V("x"),V("x"))));m.body->stmts.push_back(Decl("int","i",I(1)));{auto b=std::make_unique<Block>();b->stmts.push_back(Set("term",Bn("/",Bn("*",V("term"),Neg(V("xx"))),Bn("*",Bn("+",Bn("*",I(2),V("i")),I(1)),Bn("+",Bn("*",I(2),V("i")),I(2))))));b->stmts.push_back(Set("sum",Bn("+",V("sum"),V("term"))));b->stmts.push_back(Set("i",Bn("+",V("i"),I(1))));m.body->stmts.push_back(Loop(Bn("<",V("i"),I(10)),std::move(b)));}m.body->stmts.push_back(Ret(V("sum")));c.methods.push_back(std::move(m));m=M1("double","__native_math_cos","double","x");m.body->stmts.push_back(Ret(C1("__native_math_sin",Bn("+",V("x"),D(1.5707963267948966)))));c.methods.push_back(std::move(m));m=M1("double","__native_math_tan","double","x");m.body->stmts.push_back(Ret(Bn("/",C1("__native_math_sin",V("x")),C1("__native_math_cos",V("x")))));c.methods.push_back(std::move(m));m=M2("double","__native_math_hypot","double","a","double","b");m.body->stmts.push_back(Ret(C1("__native_math_sqrt",Bn("+",Bn("*",V("a"),V("a")),Bn("*",V("b"),V("b"))))));c.methods.push_back(std::move(m));m=M2("double","__native_math_fmod","double","a","double","b");m.body->stmts.push_back(Ret(Bn("-",V("a"),Bn("*",Bn("/",V("a"),V("b")),V("b")))));c.methods.push_back(std::move(m));p.classes.push_back(std::move(c));}

}} // namespace sleela::native
