#include "sleela_audio.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iterator>
#include <vector>
namespace sleela::audio {
namespace { struct W{uint32_t r;uint16_t c;std::vector<int16_t>p;};uint16_t u16(const unsigned char*p){return p[0]|p[1]<<8;}uint32_t u32(const unsigned char*p){return p[0]|p[1]<<8|p[2]<<16|p[3]<<24;}double g(double d){return std::pow(10.0,d/20.0);}
bool read(const std::string&path,W&w,std::string&e){std::ifstream f(path,std::ios::binary);if(!f){e="cannot open input";return false;}std::vector<unsigned char>b((std::istreambuf_iterator<char>(f)),{});if(b.size()<44||std::string((char*)b.data(),4)!="RIFF"||std::string((char*)b.data()+8,4)!="WAVE"){e="unsupported WAV";return false;}size_t p=12;uint16_t bits=0;bool fmt=0,dat=0;while(p+8<=b.size()){auto n=u32(b.data()+p+4);if(p+8+n>b.size())break;if(!std::memcmp(b.data()+p,"fmt ",4)&&n>=16){w.c=u16(b.data()+p+10);w.r=u32(b.data()+p+12);bits=u16(b.data()+p+22);fmt=1;}if(!std::memcmp(b.data()+p,"data",4)&&bits==16){w.p.resize(n/2);std::memcpy(w.p.data(),b.data()+p+8,n);dat=1;}p+=8+n+(n&1);}if(!fmt||!dat||bits!=16||w.c<1||w.c>2){e="only PCM16 mono/stereo WAV is supported";return false;}return true;}}
bool validate(const Config&c,std::string&e){if(!c.sample_rate||c.inputs.empty()||c.inputs.size()>128||c.output_path.empty()){e="invalid configuration";return false;}if(!std::isfinite(c.controls.pan)||c.controls.pan<-1||c.controls.pan>1){e="pan out of range";return false;}for(auto&i:c.inputs)if(i.path.empty()||i.start_seconds<0||!std::isfinite(i.gain_db)){e="invalid input";return false;}return true;}
bool mix_wav(const Config&c,std::string&e){if(!validate(c,e))return false;std::vector<W>w(c.inputs.size());size_t frames=0;for(size_t i=0;i<c.inputs.size();++i){if(!read(c.inputs[i].path,w[i],e)||w[i].r!=c.sample_rate){if(e.empty())e="sample-rate mismatch";return false;}frames=std::max(frames,(size_t)std::llround(c.inputs[i].start_seconds*c.sample_rate)+w[i].p.size()/w[i].c);}std::vector<int16_t>o(frames*2);double lg=g(c.controls.master_gain_db)*c.controls.left_gain*(c.controls.pan>0?1-c.controls.pan:1),rg=g(c.controls.master_gain_db)*c.controls.right_gain*(c.controls.pan<0?1+c.controls.pan:1);for(size_t i=0;i<c.inputs.size();++i){size_t s=std::llround(c.inputs[i].start_seconds*c.sample_rate);double x=g(c.inputs[i].gain_db);for(size_t f=0;f<w[i].p.size()/w[i].c;++f){double l=w[i].p[f*w[i].c]*x,r=w[i].c==2?w[i].p[f*2+1]*x:l;size_t j=(s+f)*2;o[j]=(int16_t)std::clamp((double)o[j]+l*lg,-32768.0,32767.0);o[j+1]=(int16_t)std::clamp((double)o[j+1]+r*rg,-32768.0,32767.0);}}std::ofstream f(c.output_path,std::ios::binary);if(!f){e="cannot open output";return false;}auto w16=[&](uint16_t x){f.put(char(x));f.put(char(x>>8));};auto w32=[&](uint32_t x){for(int i=0;i<4;i++)f.put(char(x>>(8*i)));};uint32_t bytes=o.size()*2;f.write("RIFF",4);w32(36+bytes);f.write("WAVEfmt ",8);w32(16);w16(1);w16(2);w32(c.sample_rate);w32(c.sample_rate*4);w16(4);w16(16);f.write("data",4);w32(bytes);f.write((char*)o.data(),bytes);return f.good();}
}
