#!/usr/bin/env python3
"""Generate a conservative C/C++ function coverage inventory."""
import pathlib,re
ROOT=pathlib.Path(__file__).resolve().parents[1]
OUT=ROOT/"test-suites"/"FUNCTION.COVERAGE.md"
EXCLUDE={".git","test-suites","bash"}
FUNC=re.compile(r"(?:(?:static|inline|virtual|constexpr|extern|consteval|constinit)\\s+)*[A-Za-z_][\\w:<>,~*&\\s]*\\s+([A-Za-z_]\\w*)\\s*\\([^;{}]*\\)\\s*(?:const\\s*)?(?:noexcept\\s*)?(?:\\{|$)")
tests=[]
for p in (ROOT/"test-suites").rglob("*"):
    if p.suffix in {".c",".cpp",".h",".hpp"}:
        try: tests.append(p.read_text(errors="ignore"))
        except OSError: pass
test_text="\\n".join(tests)
rows=[]
for p in ROOT.rglob("*"):
    if p.suffix not in {".c",".cpp"} or any(x in EXCLUDE for x in p.parts): continue
    try: raw=p.read_text(errors="ignore")
    except OSError: continue
    text=re.sub(r"//.*|/\\*.*?\\*/","",raw,flags=re.S)
    seen=set()
    for m in FUNC.finditer(text):
        name=m.group(1)
        if name in {"if","for","while","switch","catch"} or name in seen: continue
        seen.add(name); line=text.count("\\n",0,m.start())+1
        refs=len(re.findall(r"\\b"+re.escape(name)+r"\\b",test_text))
        status="tested" if refs>=2 else ("integration-tested" if p.name in {"lexer.cpp","parser.cpp","semantic.cpp","annotation_pipeline.cpp","AnnotationRuntime.cpp"} else "compile-only")
        rows.append((str(p.relative_to(ROOT)),line,name,status))
rows.sort()
counts={s:sum(r[3]==s for r in rows) for s in ("tested","integration-tested","compile-only","untested")}
lines=["# SLeeLa Function Coverage Inventory","","Generated by `test-suites/generate-function-coverage.py`.","","**Important:** source inventory and test-mapping heuristic, not runtime instrumentation. `tested` means a behavioral test source references the function; `integration-tested` means its translation unit is in the explicit annotation integration path; `compile-only` means discovered but no behavioral mapping. `untested` is reserved for functions lacking both test and compile evidence.","","| Status | Count |","|---|---:|"]
lines += [f"| {s} | {counts[s]} |" for s in ("tested","integration-tested","compile-only","untested")]
lines += ["","## Inventory","","| Source | Line | Function | Status |","|---|---:|---|---|"]
lines += [f"| `{p}` | {ln} | `{fn}()` | **{st}** |" for p,ln,fn,st in rows]
OUT.write_text("\\n".join(lines)+"\\n")
print(f"Generated {OUT} with {len(rows)} functions")