<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:sleela:bodi:1"
           xmlns="urn:sleela:bodi:1"
           elementFormDefault="qualified">
    <xs:element name="bodi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum" type="xs:string" minOccurs="0"/>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
            </xs:sequence>
            <xs:attribute name="system" type="xs:string" use="required"/>
            <xs:attribute name="method" type="xs:string" use="required"/>
            <xs:attribute name="sequence" type="xs:string" use="optional"/>
            <xs:attribute name="starter" type="xs:string" use="optional"/>
            <xs:attribute name="man" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
