#include "sleela_design_activity.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
static int finite01(double x){return isfinite(x)&&x>=0.0&&x<=1.0;}
int slda_normalize(const double raw[SLDA_DIMENSIONS],SLDA_Vector*out){if(!raw||!out)return-1;for(int i=0;i<SLDA_DIMENSIONS;i++){if(!isfinite(raw[i])||raw[i]<0.0||raw[i]>100.0)return-2;out->value[i]=raw[i]/100.0;}return 0;}
int slda_science_profile(SLDA_ScienceDomain d,SLDA_Vector*out){if(!out)return-1;switch(d){case SLDA_SCIENCE_MATH:*out=(SLDA_Vector){{1,.95,.75,.90,.80,.80}};break;case SLDA_SCIENCE_PHYSICS:*out=(SLDA_Vector){{.98,.95,1,.95,.85,.85}};break;case SLDA_SCIENCE_CHEMISTRY:*out=(SLDA_Vector){{.98,.95,1,1,.85,.85}};break;case SLDA_SCIENCE_ECONOMICS:*out=(SLDA_Vector){{.95,.95,.90,.90,.90,.90}};break;case SLDA_SCIENCE_INFERENCE:*out=(SLDA_Vector){{.98,.98,.95,.95,.85,.90}};break;case SLDA_SCIENCE_FINANCE:*out=(SLDA_Vector){{.98,.98,.98,1,.95,.90}};break;case SLDA_SCIENCE_DATA_ANALYTICS:*out=(SLDA_Vector){{.95,.98,1,.95,.90,.95}};break;case SLDA_SCIENCE_GENERAL:*out=(SLDA_Vector){{.95,.95,.95,.95,.90,.90}};break;default:return-2;}return 0;}
int slda_compare(const SLDA_Vector*n,const SLDA_Vector*e,SLDA_Result*out){if(!n||!e||!out)return-1;double sum=0;out->version=SLDA_VERSION;for(int i=0;i<SLDA_DIMENSIONS;i++){if(!finite01(n->value[i])||!finite01(e->value[i]))return-2;out->normalized.value[i]=n->value[i];out->expected.value[i]=e->value[i];double d=n->value[i]-e->value[i];sum+=d*d;}out->mean_squared_variance=sum/SLDA_DIMENSIONS;out->rms_deviation=sqrt(out->mean_squared_variance);out->l2_distance=sqrt(sum);return 0;}
const char*slda_domain_name(SLDA_ScienceDomain d){switch(d){case SLDA_SCIENCE_MATH:return "math";case SLDA_SCIENCE_PHYSICS:return "physics";case SLDA_SCIENCE_CHEMISTRY:return "chemistry";case SLDA_SCIENCE_ECONOMICS:return "economics";case SLDA_SCIENCE_INFERENCE:return "inference";case SLDA_SCIENCE_FINANCE:return "finance";case SLDA_SCIENCE_DATA_ANALYTICS:return "data-analytics";default:return "general";}}
int slda_parse_domain(const char*n,SLDA_ScienceDomain*out){if(!n||!out)return-1;const char*a[]={"general","math","physics","chemistry","economics","inference","finance","data-analytics"};for(int i=0;i<8;i++)if(strcmp(n,a[i])==0){*out=(SLDA_ScienceDomain)i;return 0;}return-2;}
int slda_format_json(const char*exe,const SLDA_Result*r,char*b,size_t cap){if(!exe||!r||!b||!cap)return-1;return snprintf(b,cap,"{\"design_activity_version\":%d,\"executable\":\"%s\",\"science\":\"%s\",\"variance\":%.17g,\"rms_deviation\":%.17g,\"l2_distance\":%.17g}",r->version,exe,slda_domain_name(r->domain),r->mean_squared_variance,r->rms_deviation,r->l2_distance);}
