#include "sleela_memmgr_grade2.h"
#include <string.h>
static int valid(const SLMMGrade2*m,unsigned s){return m&&m->initialized&&s<SLMM_G2_MAX_PROCESSES&&m->process[s].active;}
int slmm_g2_init(SLMMGrade2*m,size_t limit){if(!m||!limit)return -1;memset(m,0,sizeof(*m));m->initialized=1;m->aggregate_limit=limit;return 0;}
int slmm_g2_spawn(SLMMGrade2*m,uint64_t id,size_t limit,unsigned*slot){if(!m||!m->initialized||!limit||m->active_processes>=SLMM_G2_MAX_PROCESSES)return -1;for(unsigned i=0;i<SLMM_G2_MAX_PROCESSES;i++)if(!m->process[i].active){SLMMProcessStats*p=&m->process[i];memset(p,0,sizeof(*p));p->active=1;p->id=id;p->limit_bytes=limit;m->active_processes++;if(slot)*slot=i;return 0;}return -1;}
int slmm_g2_reserve(SLMMGrade2*m,unsigned s,size_t b){if(!valid(m,s))return -1;SLMMProcessStats*p=&m->process[s];if(b>SIZE_MAX-p->live_bytes||b>SIZE_MAX-m->aggregate_live||p->live_bytes+b>p->limit_bytes||m->aggregate_live+b>m->aggregate_limit){p->refused++;return -1;}p->live_bytes+=b;m->aggregate_live+=b;if(p->live_bytes>p->peak_bytes)p->peak_bytes=p->live_bytes;if(m->aggregate_live>m->aggregate_peak)m->aggregate_peak=m->aggregate_live;p->allocations++;return 0;}
void slmm_g2_release(SLMMGrade2*m,unsigned s,size_t b){if(!valid(m,s))return;SLMMProcessStats*p=&m->process[s];if(b>p->live_bytes)b=p->live_bytes;p->live_bytes-=b;if(b>m->aggregate_live)b=m->aggregate_live;m->aggregate_live-=b;p->frees++;}
void slmm_g2_close(SLMMGrade2*m,unsigned s){if(!valid(m,s))return;SLMMProcessStats*p=&m->process[s];if(p->live_bytes<=m->aggregate_live)m->aggregate_live-=p->live_bytes;memset(p,0,sizeof(*p));if(m->active_processes)m->active_processes--;}
int slmm_g2_stats(const SLMMGrade2*m,unsigned s,SLMMProcessStats*out){if(!valid(m,s)||!out)return -1;*out=m->process[s];return 0;}
int slmm_g2_validate(const SLMMGrade2*m){if(!m||!m->initialized||m->aggregate_live>m->aggregate_limit||m->active_processes>SLMM_G2_MAX_PROCESSES)return 0;size_t sum=0;unsigned n=0;for(unsigned i=0;i<SLMM_G2_MAX_PROCESSES;i++)if(m->process[i].active){if(m->process[i].live_bytes>m->process[i].limit_bytes)return 0;sum+=m->process[i].live_bytes;n++;}return n==m->active_processes&&sum==m->aggregate_live;}