#include "preferred_router.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cctype>
#include <string>
static void trim_cpp(char *s){size_t n;if(!s)return;while(std::isspace((unsigned char)*s))std::memmove(s,s+1,std::strlen(s));n=std::strlen(s);while(n&&std::isspace((unsigned char)s[n-1]))s[--n]='\0';}
static int kv_cpp(const char *line,const char *key,char *out,size_t cap){size_t k=std::strlen(key);if(std::strncmp(line,key,k)!=0||line[k]!='=')return 0;std::snprintf(out,cap,"%s",line+k+1);trim_cpp(out);return 1;}
static int score_cpp(const char *role){if(!std::strcmp(role,"national_backbone")||!std::strcmp(role,"national_ixp"))return 5;if(!std::strcmp(role,"regional_carrier")||!std::strcmp(role,"international_dc"))return 4;return 1;}
extern "C" int sleela_preferred_router_select(const char *config_path,const char *protocol,sleela_preferred_router *out){FILE *f;char line[512],country[16]="US",role[64]="national_backbone",candidate[256]="";int min_score=4,international=1;if(!out)return -1;std::memset(out,0,sizeof(*out));const char *cfg=config_path;if(!cfg||!*cfg)cfg=std::getenv("SLEELA_PREFERRED_ROUTER_CONFIG");if(!cfg||!*cfg)cfg="preferred-routers/preferred-routers.conf";f=std::fopen(cfg,"r");if(!f)return -2;if(f){while(std::fgets(line,sizeof line,f)){trim_cpp(line);if(!line[0]||line[0]=='#')continue;char v[256];if(kv_cpp(line,"country",country,sizeof country)){}else if(kv_cpp(line,"preferred_role",role,sizeof role)){}else if(kv_cpp(line,"min_score",v,sizeof v))min_score=std::atoi(v);else if(kv_cpp(line,"international",v,sizeof v))international=std::atoi(v)!=0;else if(kv_cpp(line,"candidate",candidate,sizeof candidate)){}}}std::fclose(f);if(min_score<1)min_score=1;if(min_score>5)min_score=5;if(score_cpp(role)<min_score)std::snprintf(role,sizeof role,"%s",min_score<=4?"regional_carrier":"national_backbone");if(!candidate[0])std::snprintf(candidate,sizeof candidate,"%s — configured %s anchor",country,role);std::snprintf(out->country,sizeof out->country,"%s",country);std::snprintf(out->role,sizeof out->role,"%s",role);std::snprintf(out->candidate,sizeof out->candidate,"%s",candidate);out->routing_preference=score_cpp(role);(void)protocol;(void)international;return 0;}
extern "C" int sleela_preferred_router_startup(const char *config_path,const char *protocol){sleela_preferred_router r;int rc=sleela_preferred_router_select(config_path,protocol,&r);if(rc!=0)return rc;std::fprintf(stderr,"SLeeLa preferred-router protocol=%s country=%s role=%s preference=%d candidate=%s\n",protocol?protocol:"HTTP",r.country,r.role,r.routing_preference,r.candidate);return 0;}
namespace sleela_preferred_routers { std::string describe(const sleela_preferred_router& r){return std::string("country=")+r.country+" role="+r.role+" preference="+std::to_string(r.routing_preference)+" candidate="+r.candidate;} }
