#include "http90.h"
#include <string.h>
static void copy_text(char *dst,size_t size,const char *src){if(!dst||size==0)return;if(!src){dst[0]='\0';return;}strncpy(dst,src,size-1);dst[size-1]='\0';}
void http90_init(http90_packet_metadata *m){if(!m)return;memset(m,0,sizeof(*m));copy_text(m->protocol_grade,sizeof(m->protocol_grade),HTTP90_VERSION);copy_text(m->identity.police_id,sizeof(m->identity.police_id),"POLICE-ID-UNASSIGNED");copy_text(m->identity.international_id,sizeof(m->identity.international_id),"INTERNATIONAL-ID-UNASSIGNED");copy_text(m->monitoring.police_scanner_frequency.value,sizeof(m->monitoring.police_scanner_frequency.value),"DISABLED");copy_text(m->monitoring.international_police_monitoring_frequency.value,sizeof(m->monitoring.international_police_monitoring_frequency.value),"DISABLED");copy_text(m->dark_band.name,sizeof(m->dark_band.name),"Dark Band");copy_text(m->dark_band.original_content_hex,sizeof(m->dark_band.original_content_hex),HTTP90_DARK_BAND_ORIGINAL_CONTENT_HEX);}
int http90_set_identity(http90_packet_metadata *m,const char *p,const char *i){if(!m||!p||!i)return HTTP90_INVALID_ARGUMENT;copy_text(m->identity.police_id,sizeof(m->identity.police_id),p);copy_text(m->identity.international_id,sizeof(m->identity.international_id),i);return HTTP90_OK;}
int http90_set_frequency(http90_frequency *f,const char *v,int e){if(!f||!v)return HTTP90_INVALID_ARGUMENT;copy_text(f->value,sizeof(f->value),v);f->enabled=e?1:0;return HTTP90_OK;}
int http90_set_national_signal_frequency(http90_packet_metadata *m,const char *emblem,const char *signal,const char *unit,const char *range,const char *jurisdiction,const char *source,const char *timestamp){if(!m||!emblem||!signal||!unit||!range||!jurisdiction||!source||!timestamp)return HTTP90_INVALID_ARGUMENT;copy_text(m->national_signal_frequency.emblem,sizeof(m->national_signal_frequency.emblem),emblem);copy_text(m->national_signal_frequency.signal,sizeof(m->national_signal_frequency.signal),signal);copy_text(m->national_signal_frequency.frequency_unit,sizeof(m->national_signal_frequency.frequency_unit),unit);copy_text(m->national_signal_frequency.frequency_range,sizeof(m->national_signal_frequency.frequency_range),range);copy_text(m->national_signal_frequency.jurisdiction,sizeof(m->national_signal_frequency.jurisdiction),jurisdiction);copy_text(m->national_signal_frequency.source,sizeof(m->national_signal_frequency.source),source);copy_text(m->national_signal_frequency.timestamp,sizeof(m->national_signal_frequency.timestamp),timestamp);return HTTP90_OK;}
int http90_set_international_data(http90_packet_metadata *m,const char *security,const char *safety,const char *police,const char *jurisdiction,const char *organization,const char *identifier,const char *classification,const char *source,const char *timestamp){if(!m||!security||!safety||!police||!jurisdiction||!organization||!identifier||!classification||!source||!timestamp)return HTTP90_INVALID_ARGUMENT;copy_text(m->international_data.security,sizeof(m->international_data.security),security);copy_text(m->international_data.safety,sizeof(m->international_data.safety),safety);copy_text(m->international_data.police,sizeof(m->international_data.police),police);copy_text(m->international_data.jurisdiction,sizeof(m->international_data.jurisdiction),jurisdiction);copy_text(m->international_data.organization,sizeof(m->international_data.organization),organization);copy_text(m->international_data.identifier,sizeof(m->international_data.identifier),identifier);copy_text(m->international_data.classification,sizeof(m->international_data.classification),classification);copy_text(m->international_data.source,sizeof(m->international_data.source),source);copy_text(m->international_data.timestamp,sizeof(m->international_data.timestamp),timestamp);return HTTP90_OK;}
int http90_set_dark_band(http90_packet_metadata *m,const char *name,const char *original_content_hex){if(!m||!name||!original_content_hex)return HTTP90_INVALID_ARGUMENT;copy_text(m->dark_band.name,sizeof(m->dark_band.name),name);copy_text(m->dark_band.original_content_hex,sizeof(m->dark_band.original_content_hex),original_content_hex);return HTTP90_OK;}
int http90_validate(const http90_packet_metadata *m){if(!m)return HTTP90_INVALID_ARGUMENT;if(!m->protocol_grade[0]||!m->identity.police_id[0]||!m->identity.international_id[0])return HTTP90_INVALID_METADATA;if(m->monitoring.police_scanner_frequency.enabled&&!strcmp(m->monitoring.police_scanner_frequency.value,"DISABLED"))return HTTP90_NOT_CONFIGURED;if(m->monitoring.international_police_monitoring_frequency.enabled&&!strcmp(m->monitoring.international_police_monitoring_frequency.value,"DISABLED"))return HTTP90_NOT_CONFIGURED;if(!m->international_data.security[0]||!m->international_data.safety[0]||!m->international_data.police[0])return HTTP90_INVALID_METADATA;if(!m->dark_band.name[0]||!m->dark_band.original_content_hex[0])return HTTP90_INVALID_METADATA;return HTTP90_OK;}
int http90_can_transmit(const http90_packet_metadata *m){return http90_validate(m)==HTTP90_OK;}
int http90_can_receive(const http90_packet_metadata *m){return http90_validate(m)==HTTP90_OK;}