#include "../include/skya_driver_runtime.h"
#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
struct skya_driver_runtime { pthread_mutex_t lock; pthread_cond_t ready; skya_driver_message *q; size_t cap,head,tail,count; uint64_t next_sequence; int running,cancel_wait; };
static uint64_t now_ns(void){struct timespec t;clock_gettime(CLOCK_REALTIME,&t);return(uint64_t)t.tv_sec*1000000000ull+(uint64_t)t.tv_nsec;}
int skya_driver_runtime_init(skya_driver_runtime **out,size_t capacity){if(!out)return-1;if(capacity<2||capacity>SKYA_DRIVER_QUEUE_CAPACITY)capacity=SKYA_DRIVER_QUEUE_CAPACITY;skya_driver_runtime*r=calloc(1,sizeof*r);if(!r)return-2;r->q=calloc(capacity,sizeof*r->q);if(!r->q){free(r);return-3;}r->cap=capacity;r->next_sequence=1;if(pthread_mutex_init(&r->lock,0)||pthread_cond_init(&r->ready,0)){free(r->q);free(r);return-4;}*out=r;return 0;}
void skya_driver_runtime_destroy(skya_driver_runtime*r){if(!r)return;pthread_mutex_lock(&r->lock);r->running=0;r->cancel_wait=1;pthread_cond_broadcast(&r->ready);pthread_mutex_unlock(&r->lock);pthread_cond_destroy(&r->ready);pthread_mutex_destroy(&r->lock);free(r->q);free(r);}
int skya_driver_runtime_start(skya_driver_runtime*r){if(!r)return-1;pthread_mutex_lock(&r->lock);r->running=1;r->cancel_wait=0;pthread_cond_broadcast(&r->ready);pthread_mutex_unlock(&r->lock);return 0;}
int skya_driver_runtime_stop(skya_driver_runtime*r){if(!r)return-1;pthread_mutex_lock(&r->lock);r->running=0;r->cancel_wait=1;pthread_cond_broadcast(&r->ready);pthread_mutex_unlock(&r->lock);return 0;}
int skya_driver_runtime_send(skya_driver_runtime*r,skya_message_type type,const void*d,size_t n,uint64_t*s){if(!r||(!d&&n)||n>SKYA_DRIVER_MESSAGE_MAX)return-1;pthread_mutex_lock(&r->lock);if(!r->running||r->count==r->cap){int e=r->count==r->cap?-2:-3;pthread_mutex_unlock(&r->lock);return e;}skya_driver_message*m=&r->q[r->tail];m->sequence=r->next_sequence++;m->timestamp_ns=now_ns();m->type=type;m->length=n;if(n)memcpy(m->data,d,n);r->tail=(r->tail+1)%r->cap;r->count++;if(s)*s=m->sequence;pthread_cond_signal(&r->ready);pthread_mutex_unlock(&r->lock);return 0;}
int skya_driver_runtime_receive(skya_driver_runtime*r,skya_driver_message*out,int wait_ms){if(!r||!out)return-1;pthread_mutex_lock(&r->lock);while(r->count==0&&!r->cancel_wait){if(wait_ms<0)pthread_cond_wait(&r->ready,&r->lock);else{struct timespec ts;clock_gettime(CLOCK_REALTIME,&ts);ts.tv_sec+=wait_ms/1000;ts.tv_nsec+=(long)(wait_ms%1000)*1000000L;if(ts.tv_nsec>=1000000000L){++ts.tv_sec;ts.tv_nsec-=1000000000L;}if(pthread_cond_timedwait(&r->ready,&r->lock,&ts)==ETIMEDOUT){pthread_mutex_unlock(&r->lock);return 1;}}}if(r->count==0){r->cancel_wait=0;pthread_mutex_unlock(&r->lock);return 2;}*out=r->q[r->head];r->head=(r->head+1)%r->cap;--r->count;pthread_mutex_unlock(&r->lock);return 0;}
int skya_driver_runtime_cancel_wait(skya_driver_runtime*r){if(!r)return-1;pthread_mutex_lock(&r->lock);r->cancel_wait=1;pthread_cond_broadcast(&r->ready);pthread_mutex_unlock(&r->lock);return 0;} int skya_driver_runtime_lock(skya_driver_runtime*r){return r?pthread_mutex_lock(&r->lock):-1;} int skya_driver_runtime_unlock(skya_driver_runtime*r){return r?pthread_mutex_unlock(&r->lock):-1;} int skya_driver_runtime_is_running(const skya_driver_runtime*r){return r?r->running:0;} size_t skya_driver_runtime_depth(const skya_driver_runtime*r){return r?r->count:0;}
