#include "permissible.h"
#include <sstream>
namespace sleela { namespace permissible {
static std::string trim(const std::string&s){size_t a=s.find_first_not_of(" \t\r");if(a==std::string::npos)return "";size_t b=s.find_last_not_of(" \t\r");return s.substr(a,b-a+1);}
static bool starts(const std::string&s,const std::string&p){return s.rfind(p,0)==0;}
static Domain domainOf(const std::string&v){if(v=="sight")return Domain::Sight;if(v=="name")return Domain::Name;if(v=="travel")return Domain::Travel;if(v=="process")return Domain::Process;if(v=="memory")return Domain::Memory;if(v=="linear-graph")return Domain::LinearGraph;return Domain::System;}
std::vector<Import> discoverAll(const std::string&source,const std::string&){std::vector<Import>out;std::istringstream in(source);std::string line;size_t n=0;while(std::getline(in,line)){++n;std::string t=trim(line);if(starts(t,"import :: permissible :: connector :: ")){std::string r=trim(t.substr(38));if(!r.empty()&&r.back()==';')r.pop_back();Import m;m.present=true;m.line=n;size_t s=r.find(" :: ");if(s!=std::string::npos){m.referenceName=trim(r.substr(0,s));m.sourcePath=trim(r.substr(s+4));}else m.sourcePath=trim(r);out.push_back(m);continue;}if(starts(t,"import permissible connector ")){std::string r=trim(t.substr(29));if(!r.empty()&&r.back()==';')r.pop_back();Import m;m.present=true;m.line=n;size_t e=r.find(" = ");if(e!=std::string::npos){m.referenceName=trim(r.substr(0,e));m.sourcePath=trim(r.substr(e+3));}else m.sourcePath=trim(r);out.push_back(m);continue;}if(starts(t,"permissible domain ")){std::string r=trim(t.substr(19));if(!r.empty()&&r.back()==';')r.pop_back();std::string ref;size_t s=r.find(" :: ");if(s!=std::string::npos){ref=trim(r.substr(0,s));r=trim(r.substr(s+4));}if(!out.empty()){size_t z=out.size()-1;if(!ref.empty())for(size_t i=0;i<out.size();++i)if(out[i].referenceName==ref){z=i;break;}out[z].domain=domainOf(r);}continue;}if(starts(t,"permissible config ")){std::string r=trim(t.substr(20));if(!r.empty()&&r.back()==';')r.pop_back();std::string ref;size_t s=r.find(" :: ");if(s!=std::string::npos){ref=trim(r.substr(0,s));r=trim(r.substr(s+4));}if(!out.empty()){size_t z=out.size()-1;if(!ref.empty())for(size_t i=0;i<out.size();++i)if(out[i].referenceName==ref){z=i;break;}out[z].configName=r;}continue;}if(starts(t,"permissible property ")){std::string r=trim(t.substr(22));if(!r.empty()&&r.back()==';')r.pop_back();std::string ref;size_t s=r.find(" :: ");if(s!=std::string::npos){ref=trim(r.substr(0,s));r=trim(r.substr(s+4));}size_t e=r.find('=');if(e!=std::string::npos&&!out.empty()){size_t z=out.size()-1;if(!ref.empty())for(size_t i=0;i<out.size();++i)if(out[i].referenceName==ref){z=i;break;}out[z].properties.push_back({trim(r.substr(0,e)),trim(r.substr(e+1))});}}}return out;}
Import discover(const std::string&s,const std::string&p){auto a=discoverAll(s,p);if(a.empty()){Import m;m.sourcePath=p;return m;}return a.front();}
bool isAdmissible(const Import&m){return m.present&&!m.sourcePath.empty();}
}}
