# Sleela Script source/default configuration
# Max Rupplin - MEARVK LLC - 2026

[scripting]
version = "1"
enabled = true
default_extension = ".sleela-script"
max_steps = 1000000
max_recursion = 256
module_root = ""
restricted_mode = true
