#!/usr/bin/env sh
# metatag — file-metatag indexer / search front end for MT-META-0001.
#
# Reads `@MT:<TAGS>` markers from files in the repo, validates them against
# METATAGS.sheet, and generates METATAGS.index (both file->tags and tag->files).
# Also a search front end (`find`) over the same markers.
#
# Portable POSIX sh; no build step. From the repo root:
#   impl/metatag/metatag.sh scan            # validate all markers
#   impl/metatag/metatag.sh index           # (re)generate METATAGS.index
#   impl/metatag/metatag.sh find P          # files bearing tag P
#   impl/metatag/metatag.sh find --primary T# files whose PRIMARY tag is T
#   impl/metatag/metatag.sh find W H        # files bearing W AND H

set -eu

MARKER='@MT:'
CANON='PMRTCSXLGAWNVDHE'          # canonical order (Code then Concern)
# Resolve repo root as the parent of impl/ (two dirs up from this script).
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
INDEX="$REPO_ROOT/METATAGS.index"

# List tracked, tagged files (skip .git; grep for the marker literal).
tagged_files() {
  # A real marker is @MT: immediately followed by >=1 upper-case letters.
  # -r recursive, -l list files, -I skip binary, -E extended regex.
  grep -rIlE -- "$MARKER[A-Z]+" "$REPO_ROOT" 2>/dev/null \
    | grep -v '/\.git/' \
    | grep -v '/METATAGS\.index$' \
    | grep -v '/metatag/metatag\.sh$' \
    | sed "s#^$REPO_ROOT/##" \
    | sort
}

# Extract the tag string for a file (first @MT: marker on the file).
tags_of() {
  # $1 = path relative to repo root
  grep -o -- "$MARKER[A-Z]*" "$REPO_ROOT/$1" 2>/dev/null \
    | head -1 | sed "s#$MARKER##"
}

# Return 0 if $1 is in canonical order and all letters are legal.
check_canon() {
  s=$1
  # rebuild the string by walking CANON; letters must appear in that order.
  rebuilt=''
  i=1
  len=$(printf %s "$CANON" | wc -c)
  while [ "$i" -le "$len" ]; do
    ch=$(printf %s "$CANON" | cut -c "$i")
    case "$s" in
      *"$ch"*) rebuilt="$rebuilt$ch" ;;
    esac
    i=$((i + 1))
  done
  [ "$rebuilt" = "$s" ]
}

cmd_scan() {
  rc=0
  for f in $(tagged_files); do
    t=$(tags_of "$f")
    if [ -z "$t" ]; then
      echo "ERROR  $f: marker present but no tags" >&2; rc=1; continue
    fi
    if ! check_canon "$t"; then
      echo "ERROR  $f: tags '$t' not in canonical order or illegal letter (order: $CANON)" >&2
      rc=1; continue
    fi
    echo "ok     $f  [$t]"
  done
  return $rc
}

cmd_index() {
  {
    echo "# METATAGS.index — GENERATED by impl/metatag/metatag.sh; do not edit."
    echo "# series MT-META-0001 ; regenerate with: impl/metatag/metatag.sh index"
    echo
    echo "section by-file:"
    for f in $(tagged_files); do
      t=$(tags_of "$f")
      printf '  %s\n    tags: %s\n' "$f" "$t"
    done
    echo
    echo "section by-tag:"
    i=1
    len=$(printf %s "$CANON" | wc -c)
    while [ "$i" -le "$len" ]; do
      ch=$(printf %s "$CANON" | cut -c "$i")
      files=''
      for f in $(tagged_files); do
        t=$(tags_of "$f")
        case "$t" in *"$ch"*) files="$files $f" ;; esac
      done
      [ -n "$files" ] && printf '  %s:%s\n' "$ch" "$files"
      i=$((i + 1))
    done
  } > "$INDEX"
  echo "wrote $INDEX"
}

cmd_find() {
  primary=0
  if [ "${1:-}" = "--primary" ]; then primary=1; shift; fi
  [ "$#" -ge 1 ] || { echo "usage: metatag find [--primary] <TAG> [TAG...]" >&2; return 2; }
  for f in $(tagged_files); do
    t=$(tags_of "$f")
    match=1
    for want in "$@"; do
      if [ "$primary" -eq 1 ]; then
        first=$(printf %s "$t" | cut -c1)
        [ "$first" = "$want" ] || match=0
      else
        case "$t" in *"$want"*) : ;; *) match=0 ;; esac
      fi
    done
    [ "$match" -eq 1 ] && echo "$f  [$t]"
  done
}

sub=${1:-}; [ "$#" -ge 1 ] && shift || true
case "$sub" in
  scan)  cmd_scan "$@" ;;
  index) cmd_index "$@" ;;
  find)  cmd_find "$@" ;;
  *) echo "usage: metatag {scan|index|find} ..." >&2; exit 2 ;;
esac
