// economics_native.cpp -- Native Economics subject library.
//
// Synthesizes the __NativeEconomics class: executable time-value functions
// (future/present value, annuities, continuous value), rate relations
// (elasticity, real rate, Fisher nominal, doubling time), and profit/margin
// plus the GDP identity. Economic results are models, not empirical forecasts.
// Economics depends on Math (e.g. pow, log, exp) and requires `import math`.
#include "native_add.h"
#include "native_builders.h"

namespace sleela { namespace native {
using namespace sleela::native::builders;

void addEconomics(Program&p){ClassDecl c;c.name="__NativeEconomics";auto m=M3("double","__native_economics_future_value","double","principal","double","rate","double","periods");m.body->stmts.push_back(Ret(Bn("*",V("principal"),C2("__native_math_pow",Bn("+",D(1),V("rate")),V("periods")))));c.methods.push_back(std::move(m));m=M3("double","__native_economics_present_value","double","future","double","rate","double","periods");m.body->stmts.push_back(Ret(Bn("/",V("future"),C2("__native_math_pow",Bn("+",D(1),V("rate")),V("periods")))));c.methods.push_back(std::move(m));m=M3("double","__native_economics_annuity_present","double","payment","double","rate","double","periods");m.body->stmts.push_back(Ret(Bn("*",V("payment"),Bn("/",Bn("-",D(1),Bn("/",D(1),C2("__native_math_pow",Bn("+",D(1),V("rate")),V("periods")))),V("rate")))));c.methods.push_back(std::move(m));m=M3("double","__native_economics_annuity_future","double","payment","double","rate","double","periods");m.body->stmts.push_back(Ret(Bn("*",V("payment"),Bn("/",Bn("-",C2("__native_math_pow",Bn("+",D(1),V("rate")),V("periods")),D(1)),V("rate")))));c.methods.push_back(std::move(m));m=M2("double","__native_economics_elasticity","double","pct_quantity","double","pct_price");m.body->stmts.push_back(Ret(Bn("/",V("pct_quantity"),V("pct_price"))));c.methods.push_back(std::move(m));m=M2("double","__native_economics_real_rate","double","nominal","double","inflation");m.body->stmts.push_back(Ret(Bn("-",Bn("/",Bn("+",D(1),V("nominal")),Bn("+",D(1),V("inflation"))),D(1))));c.methods.push_back(std::move(m));m=M2("double","__native_economics_fisher_nominal","double","real","double","inflation");m.body->stmts.push_back(Ret(Bn("-",Bn("*",Bn("+",D(1),V("real")),Bn("+",D(1),V("inflation"))),D(1))));c.methods.push_back(std::move(m));m=M1("double","__native_economics_doubling_time","double","rate");m.body->stmts.push_back(Ret(Bn("/",C1("__native_math_log",D(2)),C1("__native_math_log",Bn("+",D(1),V("rate"))))));c.methods.push_back(std::move(m));m=M3("double","__native_economics_continuous_value","double","principal","double","rate","double","time");m.body->stmts.push_back(Ret(Bn("*",V("principal"),C1("__native_math_exp",Bn("*",V("rate"),V("time"))))));c.methods.push_back(std::move(m));m=M2("double","__native_economics_profit","double","revenue","double","cost");m.body->stmts.push_back(Ret(Bn("-",V("revenue"),V("cost"))));c.methods.push_back(std::move(m));m=M2("double","__native_economics_margin","double","profit","double","revenue");m.body->stmts.push_back(Ret(Bn("/",V("profit"),V("revenue"))));c.methods.push_back(std::move(m));m=M3("double","__native_economics_gdp_identity","double","C","double","I","double","G");m.body->stmts.push_back(Ret(Bn("+",Bn("+",V("C"),V("I")),V("G"))));c.methods.push_back(std::move(m));p.classes.push_back(std::move(c));}

}} // namespace sleela::native
