package com.mearvk.sleela.skya;
import javafx.application.Application; import javafx.scene.Scene; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.stage.Stage;
import java.io.*; import java.nio.file.*;
public final class SkyaApp extends Application {
 private Label engineStatus,circuitStatus;
 public void start(Stage stage){ stage.setTitle("Skya — SLeeLa Telephony"); engineStatus=new Label("Client: starting"); circuitStatus=new Label("Monitoring circuit: loading"); ListView<String> peers=new ListView<>(); peers.getItems().addAll("Monitoring circuit initialized","Awaiting connected peers"); Button start=new Button("Start Client"), stop=new Button("Stop Monitor"); start.setOnAction(e->engineStatus.setText("Client: running")); stop.setOnAction(e->engineStatus.setText("Client: monitor stopped")); VBox center=new VBox(10,new Label("Skya Client Monitor"),new Separator(),new Label("Connection / Peer Monitor"),peers,new Label("Engine"),engineStatus,new Label("SLeeLa .sleela circuit"),circuitStatus); root(stage,new HBox(8,start,stop),center); runSleelaMonitoringCircuit(); }
 private void root(Stage s,HBox top,VBox center){ BorderPane r=new BorderPane(); r.setPadding(new javafx.geometry.Insets(12)); r.setTop(top); r.setCenter(center); s.setScene(new Scene(r,760,520)); s.show(); }
 private void runSleelaMonitoringCircuit(){ Path c=locateCircuit(); if(c==null){circuitStatus.setText("Monitoring circuit: not found");return;} circuitStatus.setText("Monitoring circuit: "+c); String cmd=System.getenv("SLEELA_COMMAND"); if(cmd==null||cmd.isBlank())cmd="sleela"; try{Process p=new ProcessBuilder(cmd,"run",c.toString()).redirectErrorStream(true).start(); Thread.ofVirtual().start(()->{try(BufferedReader b=new BufferedReader(new InputStreamReader(p.getInputStream()))){while(b.readLine()!=null){}}catch(IOException ignored){}});}catch(IOException e){circuitStatus.setText("Circuit found; SLeeLa runner unavailable");} }
 private Path locateCircuit(){ String configured=System.getenv("SKYA_SLEEELA_CIRCUIT"); if(configured!=null&&!configured.isBlank()){Path p=Paths.get(configured);if(Files.isRegularFile(p))return p;} Path cwd=Paths.get("").toAbsolutePath(); Path p=cwd.resolve("telephony-skya/sleela/SkyaClient.sleela"); if(Files.isRegularFile(p))return p; p=cwd.resolve("sleela/SkyaClient.sleela"); return Files.isRegularFile(p)?p:null; }
 public static void main(String[] a){launch(a);}
}