package com.mearvk.sleela.synchro;
import java.io.IOException; import java.net.*; import java.nio.ByteBuffer; import java.util.*;
public final class UdpDispatcher {
 private static final int MAGIC=0x53594E43; private final InetSocketAddress[] destinations; private final int payloadBytes,timeoutMs; private long sequence; private final Map<String,SynchroStats> stats=new LinkedHashMap<>();
 public UdpDispatcher(InetSocketAddress[]d){this(d,64,500,1024);} public UdpDispatcher(InetSocketAddress[]d,int p,int t,int w){if(t<=0||w<=0)throw new IllegalArgumentException();destinations=d.clone();payloadBytes=Math.max(16,p);timeoutMs=t;for(InetSocketAddress x:d)stats.put(key(x),new SynchroStats(key(x),w));}
 private static String key(InetSocketAddress d){return d.getHostString()+":"+d.getPort();}
 public Map<String,SynchroStats> run(int rounds,long intervalMs)throws IOException{if(rounds<0||intervalMs<0)throw new IllegalArgumentException();try(DatagramSocket s=new DatagramSocket()){for(int r=0;r<rounds;r++){Map<Long,Sent> in=new LinkedHashMap<>();for(InetSocketAddress d:destinations){long q=++sequence,n=System.nanoTime();ByteBuffer b=ByteBuffer.allocate(payloadBytes);b.putInt(MAGIC).putInt((int)q).putLong(n);try{s.send(new DatagramPacket(b.array(),b.position(),d));in.put(q,new Sent(d,n));}catch(IOException e){stats.get(key(d)).record(null);}}long deadline=System.nanoTime()+timeoutMs*1_000_000L;while(!in.isEmpty()&&System.nanoTime()<deadline){s.setSoTimeout((int)Math.max(1,Math.min(timeoutMs,(deadline-System.nanoTime())/1_000_000L)));byte[]buf=new byte[Math.max(payloadBytes,32)];DatagramPacket p=new DatagramPacket(buf,buf.length);try{s.receive(p);if(p.getLength()>=16){ByteBuffer b=ByteBuffer.wrap(p.getData(),p.getOffset(),p.getLength());if(b.getInt()==MAGIC){long q=Integer.toUnsignedLong(b.getInt());b.getLong();Sent z=in.remove(q);if(z!=null)stats.get(key(z.d)).record((System.nanoTime()-z.n)/1e6);}}}catch(SocketTimeoutException e){break;}}for(Sent z:in.values())stats.get(key(z.d)).record(null);if(intervalMs>0)try{Thread.sleep(intervalMs);}catch(InterruptedException e){Thread.currentThread().interrupt();}}}return stats;}
 public static void echoServer(InetSocketAddress bind,int stopAfter)throws IOException{try(DatagramSocket s=new DatagramSocket(bind)){int n=0;byte[]buf=new byte[65535];while(stopAfter<0||n<stopAfter){DatagramPacket p=new DatagramPacket(buf,buf.length);s.receive(p);if(p.getLength()>=16&&ByteBuffer.wrap(p.getData(),p.getOffset(),p.getLength()).getInt()==MAGIC){s.send(new DatagramPacket(p.getData(),p.getLength(),p.getSocketAddress()));n++;}}}}
 private record Sent(InetSocketAddress d,long n){}
}