param(
  [string]$Destination = "",
  [switch]$NoBuild
)
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
if ([string]::IsNullOrWhiteSpace($Destination)) { $Destination = Join-Path $env:LOCALAPPDATA "SLeeLa" }

function Ask-YesNo([string]$Prompt, [string]$Default) {
  $v = Read-Host "$Prompt [$Default]"
  if ([string]::IsNullOrWhiteSpace($v)) { $v = $Default }
  if ($v -match '^(y|yes)$') { return "yes" } else { return "no" }
}
function Ask-Value([string]$Prompt, [string]$Default) {
  $v = Read-Host "$Prompt [$Default]"
  if ([string]::IsNullOrWhiteSpace($v)) { return $Default }
  return $v
}

Write-Host "SLeeLa Quick and Safe Install"
Write-Host "Repository: $RepoRoot"
Write-Host "Destination: $Destination"

$SystemStart = Ask-YesNo "Start SLeeLa System at user login?" "yes"
$ServerStart = Ask-YesNo "Start SLeeLa Server with SLeeLa System?" "no"
$Http = @{}
1..9 | ForEach-Object { $Http[$_] = Ask-YesNo "Start HTTP Server $_?" "no" }
$VmEdition = Ask-Value "VM Edition (simple|managed|advanced)" "managed"
if ($VmEdition -notin @("simple","managed","advanced")) { throw "Invalid VM Edition" }
$PortStart = Ask-YesNo "Start Port Authority at startup?" "yes"
$PortPause = Ask-YesNo "Allow Port Authority pause?" "yes"
$PortShutdown = Ask-YesNo "Allow Port Authority shutdown?" "yes"
$PathUpdate = Ask-YesNo "Add SLeeLa bin to the user PATH?" "yes"

if (-not $NoBuild) {
  Write-Host "Building SLeeLa..."
  & make -C $RepoRoot all
  if ($LASTEXITCODE -ne 0) { throw "SLeeLa build failed; installation was not changed." }
}

$Stage = Join-Path ([System.IO.Path]::GetTempPath()) ("sleela-install-" + [guid]::NewGuid())
New-Item -ItemType Directory -Force -Path (Join-Path $Stage "lib"),(Join-Path $Stage "bin"),(Join-Path $Stage "config") | Out-Null
Copy-Item -Recurse -Force (Join-Path $RepoRoot "lib*") (Join-Path $Stage "lib")
if (Test-Path (Join-Path $RepoRoot "bin")) { Copy-Item -Recurse -Force (Join-Path $RepoRoot "bin*") (Join-Path $Stage "bin") }

@"
# Generated by SLeeLa Quick and Safe Install
system.startup=$SystemStart
server.startup=$ServerStart
http.1.startup=$($Http[1])
http.2.startup=$($Http[2])
http.3.startup=$($Http[3])
http.4.startup=$($Http[4])
http.5.startup=$($Http[5])
http.6.startup=$($Http[6])
http.7.startup=$($Http[7])
http.8.startup=$($Http[8])
http.9.startup=$($Http[9])
vm.edition=$VmEdition
port-authority.startup=$PortStart
port-authority.pause=$PortPause
port-authority.shutdown=$PortShutdown
"@ | Set-Content -Encoding UTF8 (Join-Path $Stage "configstartup.conf")

if (Test-Path $Destination) {
  $BackupRoot = Join-Path $env:LOCALAPPDATA "SLeeLa-backups"
  New-Item -ItemType Directory -Force -Path $BackupRoot | Out-Null
  $Backup = Join-Path $BackupRoot (Get-Date -Format "yyyyMMdd-HHmmss")
  Copy-Item -Recurse -Force $Destination $Backup
  Write-Host "Backup: $Backup"
}
New-Item -ItemType Directory -Force -Path $Destination | Out-Null
Copy-Item -Recurse -Force (Join-Path $Stage "*") $Destination

if ($PathUpdate -eq "yes") {
  $Current = [Environment]::GetEnvironmentVariable("Path","User")
  $Parts = @($Current -split ';' | Where-Object { $_ -and $_ -ne (Join-Path $Destination "bin") })
  [Environment]::SetEnvironmentVariable("Path", (($Parts + (Join-Path $Destination "bin")) -join ';'), "User")
  Write-Host "User PATH updated. Open a new terminal to inherit it."
}
Remove-Item -Recurse -Force $Stage
Write-Host "SLeeLa installation complete."
Write-Host "Install root: $Destination"
Write-Host "Configuration: $(Join-Path $Destination 'configstartup.conf')"
