#!/usr/bin/env bash
set -euo pipefail
# SLeeLa Quick and Safe Installer - user-local deployment.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
INSTALL_ROOT="${SLEELA_INSTALL_ROOT:-$HOME/.local/sleela}"
CONFIG_DIR="$INSTALL_ROOT/config"
STAGE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sleela-install.XXXXXX")"
BACKUP_ROOT="$HOME/.local/share/sleela-backups"
mkdir -p "$BACKUP_ROOT"
trap 'rm -rf "$STAGE_DIR"' EXIT

ask_yn() {
  local prompt="$1" default="$2" answer
  read -r -p "$prompt [$default]: " answer
  answer="${answer:-$default}"
  case "${answer,,}" in y|yes) echo "yes";; *) echo "no";; esac
}
ask_value() {
  local prompt="$1" default="$2" answer
  read -r -p "$prompt [$default]: " answer
  echo "${answer:-$default}"
}

echo "SLeeLa Quick and Safe Install"
echo "Repository: $REPO_ROOT"
echo "Destination: $INSTALL_ROOT"
echo

SYSTEM_START="$(ask_yn "Start SLeeLa System at user login?" "yes")"
SERVER_START="$(ask_yn "Start SLeeLa Server with SLeeLa System?" "no")"
HTTP1="$(ask_yn "Start HTTP Server 1?" "no")"; HTTP2="$(ask_yn "Start HTTP Server 2?" "no")"; HTTP3="$(ask_yn "Start HTTP Server 3?" "no")"
HTTP4="$(ask_yn "Start HTTP Server 4?" "no")"; HTTP5="$(ask_yn "Start HTTP Server 5?" "no")"; HTTP6="$(ask_yn "Start HTTP Server 6?" "no")"
HTTP7="$(ask_yn "Start HTTP Server 7?" "no")"; HTTP8="$(ask_yn "Start HTTP Server 8?" "no")"; HTTP9="$(ask_yn "Start HTTP Server 9?" "no")"
VM_EDITION="$(ask_value "VM Edition (simple|managed|advanced)" "managed")"
PORT_START="$(ask_yn "Start Port Authority at startup?" "yes")"
PORT_PAUSE="$(ask_yn "Allow Port Authority pause?" "yes")"
PORT_SHUTDOWN="$(ask_yn "Allow Port Authority shutdown?" "yes")"
PATH_UPDATE="$(ask_yn "Install a user-level PATH entry?" "yes")"
case "$VM_EDITION" in simple|managed|advanced) ;; *) echo "Invalid VM Edition"; exit 2;; esac

echo "Building SLeeLa..."
make -C "$REPO_ROOT" all

echo "Staging runtime..."
mkdir -p "$STAGE_DIR/lib" "$STAGE_DIR/bin" "$STAGE_DIR/config"
cp -a "$REPO_ROOT/lib/." "$STAGE_DIR/lib/"
if [ -d "$REPO_ROOT/bin" ]; then cp -a "$REPO_ROOT/bin/." "$STAGE_DIR/bin/"; fi

# Install the real built toolchain binaries. `make all` compiles the impl build
# and stages 'sleela' (and 'nordshrift') under impl/build/SLeeLa/bin; copy those
# so $SLEELA_HOME/bin actually contains the 'sleela' executable that projects
# (and the SLEELA variable) point at. Fall back to the raw build dir.
SLEELA_BIN=""
for cand in \
  "$REPO_ROOT/impl/build/SLeeLa/bin/sleela" \
  "$REPO_ROOT/impl/build/sleela" ; do
  if [ -x "$cand" ]; then SLEELA_BIN="$cand"; break; fi
done
if [ -n "$SLEELA_BIN" ]; then
  cp -a "$(dirname "$SLEELA_BIN")/." "$STAGE_DIR/bin/"
else
  echo "WARNING: built 'sleela' binary not found under impl/build; the toolchain" >&2
  echo "         may not have compiled. '$STAGE_DIR/bin' will lack 'sleela'." >&2
fi
cat > "$STAGE_DIR/config/startup.conf" <<EOF
# Generated by SLeeLa Quick and Safe Install
system.startup=$SYSTEM_START
server.startup=$SERVER_START
http.1.startup=$HTTP1
http.2.startup=$HTTP2
http.3.startup=$HTTP3
http.4.startup=$HTTP4
http.5.startup=$HTTP5
http.6.startup=$HTTP6
http.7.startup=$HTTP7
http.8.startup=$HTTP8
http.9.startup=$HTTP9
vm.edition=$VM_EDITION
port-authority.startup=$PORT_START
port-authority.pause=$PORT_PAUSE
port-authority.shutdown=$PORT_SHUTDOWN
EOF

if [ -e "$INSTALL_ROOT" ]; then
  BACKUP="$BACKUP_ROOT/$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$BACKUP"
  cp -a "$INSTALL_ROOT/." "$BACKUP/"
  echo "Backup: $BACKUP"
fi
rm -rf "$INSTALL_ROOT"
mkdir -p "$INSTALL_ROOT"
cp -a "$STAGE_DIR/." "$INSTALL_ROOT"

if [ "$PATH_UPDATE" = "yes" ]; then
  # Write a single environment snippet, then source it from whichever shell
  # startup files the user actually has. This sets SLEELA_HOME and prepends
  # the SLeeLa bin to PATH for Linux (bash) and macOS (zsh by default).
  PROFILE_DIR="$INSTALL_ROOT/profile"
  mkdir -p "$PROFILE_DIR"
  SNIPPET="$PROFILE_DIR/sleela-env.sh"
  cat > "$SNIPPET" <<EOF
# SLeeLa environment (generated by the Quick and Safe installer).
export SLEELA_HOME="$INSTALL_ROOT"
# SLEELA points at the toolchain executable (projects check this, e.g. the
# "set SLEELA=/path/to/sleela" convention); it falls back to PATH resolution.
if [ -x "\$SLEELA_HOME/bin/sleela" ]; then export SLEELA="\$SLEELA_HOME/bin/sleela"; fi
case ":\$PATH:" in
  *:"\$SLEELA_HOME/bin":*) ;;
  *) export PATH="\$SLEELA_HOME/bin:\$PATH" ;;
esac
EOF
  chmod 0644 "$SNIPPET"

  # Idempotent hook: add a guarded `source` line to each present rc file.
  HOOK_LINE="[ -f \"$SNIPPET\" ] && . \"$SNIPPET\"  # SLeeLa"
  hooked=""
  for rc in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshrc" "$HOME/.profile"; do
    [ -e "$rc" ] || { case "$rc" in */.profile) : ;; *) continue;; esac; }
    touch "$rc"
    if ! grep -qF "# SLeeLa" "$rc" 2>/dev/null; then
      printf '\n%s\n' "$HOOK_LINE" >> "$rc"
      hooked="$hooked $rc"
    fi
  done
  echo "PATH snippet: $SNIPPET"
  [ -n "$hooked" ] && echo "Hooked into:$hooked"
  echo "Run 'source $SNIPPET' (or open a new terminal) to use 'sleela' now."
fi
echo "SLeeLa installation complete."
echo "Install root: $INSTALL_ROOT"
echo "SLEELA_HOME:  $INSTALL_ROOT"
if [ -x "$INSTALL_ROOT/bin/sleela" ]; then
  echo "SLEELA:       $INSTALL_ROOT/bin/sleela"
else
  echo "SLEELA:       (not set — 'sleela' binary missing; run 'make -C \"$REPO_ROOT/impl\" all' and re-install)"
fi
echo "Configuration: $CONFIG_DIR/startup.conf"
