#!/usr/bin/env bash
set -euo pipefail
# SLeeLa Quick and Safe Installer - user-local or system-wide deployment.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
STAGE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sleela-install.XXXXXX")"
BACKUP_ROOT="$HOME/.local/share/sleela-backups"
trap 'rm -rf "$STAGE_DIR"' EXIT

ask_yn() {
  local prompt="$1" default="$2" answer
  read -r -p "$prompt [$default]: " answer
  answer="${answer:-$default}"
  case "${answer,,}" in y|yes) echo "yes";; *) echo "no";; esac
}
ask_value() {
  local prompt="$1" default="$2" answer
  read -r -p "$prompt [$default]: " answer
  echo "${answer:-$default}"
}

echo "SLeeLa Quick and Safe Install"
echo "Repository: $REPO_ROOT"
echo
echo "Installation scope:"
echo "  1) User-local (no administrator access; recommended)"
echo "  2) System-wide (/usr/local/bin and /usr/local/lib/sleela; may request sudo)"
SCOPE="$(ask_value "Choose installation scope (1|2)" "1")"
case "$SCOPE" in
  1) INSTALL_MODE=user; INSTALL_ROOT="${SLEELA_INSTALL_ROOT:-$HOME/.local/sleela}"; BIN_DEST="$INSTALL_ROOT/bin"; CONFIG_DIR="$INSTALL_ROOT/config" ;;
  2) INSTALL_MODE=system; INSTALL_ROOT="${SLEELA_SYSTEM_ROOT:-/usr/local/lib/sleela}"; BIN_DEST="/usr/local/bin"; CONFIG_DIR="/etc/sleela" ;;
  *) echo "Invalid installation scope; choose 1 or 2." >&2; exit 2 ;;
esac
echo "Destination: $INSTALL_ROOT"
echo

SYSTEM_START="$(ask_yn "Start SLeeLa System at user login?" "yes")"
SERVER_START="$(ask_yn "Start SLeeLa Server with SLeeLa System?" "no")"
HTTP1="$(ask_yn "Start HTTP Server 1?" "no")"; HTTP2="$(ask_yn "Start HTTP Server 2?" "no")"; HTTP3="$(ask_yn "Start HTTP Server 3?" "no")"
HTTP4="$(ask_yn "Start HTTP Server 4?" "no")"; HTTP5="$(ask_yn "Start HTTP Server 5?" "no")"; HTTP6="$(ask_yn "Start HTTP Server 6?" "no")"
HTTP7="$(ask_yn "Start HTTP Server 7?" "no")"; HTTP8="$(ask_yn "Start HTTP Server 8?" "no")"; HTTP9="$(ask_yn "Start HTTP Server 9?" "no")"
VM_EDITION="$(ask_value "VM Edition (simple|managed|advanced)" "managed")"
PORT_START="$(ask_yn "Start Port Authority at startup?" "yes")"
PORT_PAUSE="$(ask_yn "Allow Port Authority pause?" "yes")"
PORT_SHUTDOWN="$(ask_yn "Allow Port Authority shutdown?" "yes")"
PATH_UPDATE=no
if [ "$INSTALL_MODE" = user ]; then
  PATH_UPDATE="$(ask_yn "Install a user-level PATH entry?" "yes")"
fi
case "$VM_EDITION" in simple|managed|advanced) ;; *) echo "Invalid VM Edition"; exit 2;; esac

echo "Building SLeeLa..."
make -C "$REPO_ROOT" all

echo "Staging runtime..."
mkdir -p "$STAGE_DIR/lib" "$STAGE_DIR/bin" "$STAGE_DIR/config"
cp -a "$REPO_ROOT/lib/." "$STAGE_DIR/lib/"
if [ -d "$REPO_ROOT/bin" ]; then cp -a "$REPO_ROOT/bin/." "$STAGE_DIR/bin/"; fi
for product in sleela nordshrift; do
  built="$REPO_ROOT/impl/build/$product"
  [ -x "$built" ] || { echo "Required compiled product missing: $built" >&2; exit 1; }
  install -m 755 "$built" "$STAGE_DIR/bin/$product"
done
cat > "$STAGE_DIR/config/startup.conf" <<EOF
# Generated by SLeeLa Quick and Safe Install
install.mode=$INSTALL_MODE
install.root=$INSTALL_ROOT
system.startup=$SYSTEM_START
server.startup=$SERVER_START
http.1.startup=$HTTP1
http.2.startup=$HTTP2
http.3.startup=$HTTP3
http.4.startup=$HTTP4
http.5.startup=$HTTP5
http.6.startup=$HTTP6
http.7.startup=$HTTP7
http.8.startup=$HTTP8
http.9.startup=$HTTP9
vm.edition=$VM_EDITION
port-authority.startup=$PORT_START
port-authority.pause=$PORT_PAUSE
port-authority.shutdown=$PORT_SHUTDOWN
EOF

if [ "$INSTALL_MODE" = user ]; then
  mkdir -p "$BACKUP_ROOT"
  if [ -e "$INSTALL_ROOT" ]; then
    BACKUP="$BACKUP_ROOT/$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP"
    cp -a "$INSTALL_ROOT/." "$BACKUP/"
    echo "Backup: $BACKUP"
  fi
  mkdir -p "$INSTALL_ROOT"
  cp -a "$STAGE_DIR/." "$INSTALL_ROOT/"
  if [ "$PATH_UPDATE" = yes ]; then
    PROFILE_DIR="$HOME/.profile.d"
    mkdir -p "$PROFILE_DIR"
    cat > "$PROFILE_DIR/sleela.sh" <<EOF
export SLEELA_HOME="$INSTALL_ROOT"
case ":$PATH:" in *:"$SLEELA_HOME/bin":*) ;; *) export PATH="$SLEELA_HOME/bin:$PATH";; esac
EOF
    echo "User PATH snippet: $PROFILE_DIR/sleela.sh (source it from your shell profile if your shell does not load ~/.profile.d)"
  fi
else
  command -v sudo >/dev/null 2>&1 || { echo "System installation needs sudo or an already privileged shell." >&2; exit 1; }
  sudo mkdir -p "$INSTALL_ROOT" "$BIN_DEST" "$CONFIG_DIR" /etc/profile.d
  sudo cp -a "$STAGE_DIR/lib" "$INSTALL_ROOT/"
  sudo cp -a "$STAGE_DIR/bin/." "$INSTALL_ROOT/bin/"
  sudo cp "$STAGE_DIR/config/startup.conf" "$CONFIG_DIR/startup.conf"
  for product in sleela nordshrift; do sudo ln -sfn "$INSTALL_ROOT/bin/$product" "$BIN_DEST/$product"; done
  printf 'export SLEELA_HOME="%s"\n' "$INSTALL_ROOT" | sudo tee /etc/profile.d/sleela.sh >/dev/null
  echo "System PATH: $BIN_DEST (standard /usr/local/bin location; /etc/profile.d/sleela.sh sets SLEELA_HOME)"
fi
echo "SLeeLa installation complete."
echo "Install root: $INSTALL_ROOT"
echo "Configuration: $CONFIG_DIR/startup.conf"
