#!/usr/bin/env python3
"""Render the /lib class-vocabulary appendix shared by SLEELA.syntax, SST, and
Nordshrift.

This is an INFORMATIVE mirror of the authoritative manifest
(lib/LIBRARY.SYMBOLS.md); it is NOT a second registry. /lib + sleela::library::
Index remain the sole source of truth (see impl/nordshrift/SST.SYMBOLS.md). The
appendix exists so a reader of the language/SST/Nordshrift specs can see the
package-qualified class vocabulary that those layers resolve against.

To keep the appendix legible, any package with more than THRESHOLD classes is
summarized (count + facade) rather than listed in full; smaller packages list
every class name (without the .sleela suffix).

Usage:
  python3 tools/generate-vocab-appendix.py            # emit markdown appendix to stdout
"""
import sys
from pathlib import Path
from collections import defaultdict

THRESHOLD = 40  # packages larger than this are summarized, not fully listed


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_manifest(path: Path):
    """package -> list of (symbol_without_ext, kind)."""
    pkgs = defaultdict(list)
    for line in path.read_text().splitlines():
        if "\t" not in line:
            continue
        parts = line.split("\t")
        if len(parts) != 4 or parts[0] == "package":
            continue
        package, symbol, _p, kind = parts
        name = symbol[:-len(".sleela")] if symbol.endswith(".sleela") else symbol
        pkgs[package].append((name, kind))
    return pkgs


def render(pkgs) -> str:
    total_pkgs = len(pkgs)
    total_syms = sum(len(v) for v in pkgs.values())
    out = []
    out.append("<!-- GENERATED by tools/generate-vocab-appendix.py from "
               "lib/LIBRARY.SYMBOLS.md. Do not edit by hand; re-run the tool. -->")
    out.append("")
    out.append(
        f"This appendix mirrors the **{total_syms}** package-qualified class "
        f"symbols across **{total_pkgs}** `/lib` package families, as recorded "
        "in the authoritative manifest `lib/LIBRARY.SYMBOLS.md`. It is "
        "**informative**: `/lib` and the shared `sleela::library::Index` remain "
        "the single source of truth, and nothing here constitutes a second "
        "registry. Each entry is resolvable as `<package>.<ClassName>`. Large "
        f"auto-generated families (> {THRESHOLD} classes) are summarized by "
        "count and facade; smaller families list every class.")
    out.append("")
    for package in sorted(pkgs):
        entries = pkgs[package]
        names = sorted(n for n, _k in entries)
        if len(entries) > THRESHOLD:
            facade = "SLPackage" if any(
                n == "SLPackage" for n, _k in entries) else names[0]
            out.append(f"- **`{package}`** — {len(entries)} classes "
                       f"(facade `{package}.{facade}`); see "
                       f"`lib/LIBRARY.SYMBOLS.md` for the full list.")
        else:
            joined = ", ".join(f"`{n}`" for n in names)
            out.append(f"- **`{package}`** ({len(entries)}): {joined}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    root = repo_root()
    manifest = root / "lib" / "LIBRARY.SYMBOLS.md"
    if not manifest.is_file():
        print(f"error: {manifest} not found", file=sys.stderr)
        return 2
    pkgs = load_manifest(manifest)
    sys.stdout.write(render(pkgs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
