// ===========================================================================
// emit_java.cpp  --  Nordshrift component graph -> runnable Java source.
//
// Mapping:
//   component C            -> `static class C`
//   attach name: {..}      -> `static void C_name()`  (sanitized name)
//   prop(p)                -> the property value, inlined
//   call C.f()             -> `C_f()`
//   print(e)               -> `System.out.println(e)`
//   threads: N             -> activation runs on a fixed thread pool of N
//   on-start / tick        -> activation sequence in dependency order
//   main                   -> invoked last from Java `main`
// ===========================================================================
#include "emitters.h"

#include <sstream>
#include <string>

namespace nordshrift {
namespace {

std::string sanitize(const std::string& name) {
    std::string out;
    for (char c : name) out += (c == '-') ? '_' : c;
    return out;
}

std::string escapeJava(const std::string& s) {
    std::string o;
    for (char c : s) {
        switch (c) {
            case '"': o += "\\\""; break;
            case '\\': o += "\\\\"; break;
            case '\n': o += "\\n"; break;
            case '\t': o += "\\t"; break;
            case '\r': o += "\\r"; break;
            default: o += c;
        }
    }
    return o;
}

struct JavaEmitter {
    const Sheet& sheet;
    const Component* self = nullptr;   // current component (for prop())
    std::ostringstream out;

    explicit JavaEmitter(const Sheet& s) : sheet(s) {}

    std::string run() {
        out << "// Generated by Nordshrift (Java target)\n";
        out << "import java.util.concurrent.ExecutorService;\n";
        out << "import java.util.concurrent.Executors;\n";
        out << "import java.util.concurrent.TimeUnit;\n\n";
        out << "public class NordshriftProgram {\n\n";

        for (auto& c : sheet.components) emitComponent(c);

        emitMain();

        out << "}\n";
        return out.str();
    }

    void emitComponent(const Component& c) {
        out << "    // ---- component " << c.name << " ----\n";
        out << "    static final class " << c.name << " {\n";
        for (auto& a : c.attaches) {
            self = &c;
            out << "        static void " << sanitize(a.name) << "() {\n";
            emitBlock(*a.body, 3);
            out << "        }\n";
            self = nullptr;
        }
        out << "    }\n\n";
    }

    void indent(int n) { for (int i = 0; i < n; i++) out << "    "; }

    void emitBlock(const Block& b, int ind) {
        for (auto& s : b.stmts) emitStmt(s.get(), ind);
    }

    void emitStmt(const Stmt* s, int ind) {
        if (auto b = dynamic_cast<const Block*>(s)) { indent(ind); out << "{\n"; emitBlock(*b, ind+1); indent(ind); out << "}\n"; return; }
        if (auto l = dynamic_cast<const LetStmt*>(s)) {
            indent(ind); out << "var " << l->name << " = "; emitExpr(l->init.get()); out << ";\n"; return;
        }
        if (auto a = dynamic_cast<const AssignStmt*>(s)) {
            indent(ind); out << a->name << " = "; emitExpr(a->value.get()); out << ";\n"; return;
        }
        if (auto p = dynamic_cast<const PrintStmt*>(s)) {
            indent(ind); out << "System.out.println("; emitExpr(p->expr.get()); out << ");\n"; return;
        }
        if (auto i = dynamic_cast<const IfStmt*>(s)) {
            indent(ind); out << "if ("; emitExpr(i->cond.get()); out << ") {\n";
            emitStmt(i->thenS.get(), ind+1);
            indent(ind); out << "}";
            if (i->elseS) { out << " else {\n"; emitStmt(i->elseS.get(), ind+1); indent(ind); out << "}"; }
            out << "\n"; return;
        }
        if (auto w = dynamic_cast<const WhileStmt*>(s)) {
            indent(ind); out << "while ("; emitExpr(w->cond.get()); out << ") {\n";
            emitStmt(w->body.get(), ind+1);
            indent(ind); out << "}\n"; return;
        }
        if (auto c = dynamic_cast<const CallStmt*>(s)) {
            indent(ind); out << c->comp << "." << sanitize(c->attach) << "();\n"; return;
        }
    }

    void emitExpr(const Expr* e) {
        if (auto n = dynamic_cast<const NumLit*>(e)) {
            if (n->isInt) out << (long long)n->value; else out << n->value;
            return;
        }
        if (auto s = dynamic_cast<const StrLit*>(e)) { out << "\"" << escapeJava(s->value) << "\""; return; }
        if (auto b = dynamic_cast<const BoolLit*>(e)) { out << (b->value ? "true" : "false"); return; }
        if (auto v = dynamic_cast<const VarRef*>(e)) { out << v->name; return; }
        if (auto p = dynamic_cast<const PropRef*>(e)) { emitProp(p->name); return; }
        if (auto u = dynamic_cast<const Unary*>(e)) { out << u->op << "("; emitExpr(u->e.get()); out << ")"; return; }
        if (auto bi = dynamic_cast<const Binary*>(e)) {
            out << "("; emitExpr(bi->l.get()); out << " " << bi->op << " "; emitExpr(bi->r.get()); out << ")"; return;
        }
    }

    // Inline the current component's property value.
    void emitProp(const std::string& name) {
        if (!self) { out << "null"; return; }
        auto it = self->props.find(name);
        if (it == self->props.end()) { out << "\"\""; return; }
        const PropValue& v = it->second;
        switch (v.kind) {
            case ValKind::Number: if (v.isInt) out << (long long)v.num; else out << v.num; break;
            case ValKind::Str:    out << "\"" << escapeJava(v.s) << "\""; break;
            case ValKind::Bool:   out << (v.b ? "true" : "false"); break;
            case ValKind::Ident:  out << "\"" << escapeJava(v.s) << "\""; break;
        }
    }

    // Emit the activation of one component: on-start (x threads), tick x repeat.
    void emitActivation(const Component& c, int ind) {
        long long th = c.threads();
        bool hasStart = c.findAttach("on-start");
        bool hasTick  = c.findAttach("tick");
        if (!hasStart && !hasTick) return;

        indent(ind); out << "// activate " << c.name;
        if (th > 1) out << " on " << th << " thread(s)";
        out << "\n";

        auto body = [&](int i2) {
            if (hasStart) { indent(i2); out << c.name << "." << sanitize("on-start") << "();\n"; }
            if (hasTick) {
                indent(i2); out << "for (int _t = 0; _t < " << c.repeat() << "; _t++) "
                                << c.name << "." << sanitize("tick") << "();\n";
            }
        };

        if (th > 1) {
            indent(ind); out << "{\n";
            indent(ind+1); out << "ExecutorService _ex = Executors.newFixedThreadPool(" << th << ");\n";
            indent(ind+1); out << "for (int _w = 0; _w < " << th << "; _w++) _ex.submit(() -> {\n";
            body(ind+2);
            indent(ind+1); out << "});\n";
            indent(ind+1); out << "_ex.shutdown();\n";
            indent(ind+1); out << "try { _ex.awaitTermination(1, TimeUnit.HOURS); } catch (InterruptedException _e) {}\n";
            indent(ind); out << "}\n";
        } else {
            body(ind);
        }
    }

    void emitMain() {
        out << "    public static void main(String[] args) {\n";
        // activate components in dependency-first order
        for (int idx : sheet.order) emitActivation(sheet.components[idx], 2);
        // then run the single main attach
        const Component* mc = sheet.mainComponent();
        if (mc) { indent(2); out << mc->name << ".main();\n"; }
        out << "    }\n";
    }
};

} // namespace

std::string emitJava(const Sheet& sheet) {
    JavaEmitter e(sheet);
    return e.run();
}

} // namespace nordshrift
