// ===========================================================================
// emit_c.cpp  --  Nordshrift component graph -> runnable C source.
//
// The attach language is dynamically typed (numbers may be int or double, and
// `+` concatenates when a string is involved), so the emitted C carries a tiny
// tagged value type `nsv` plus helper ops. This mirrors the Sleela core's value
// model and keeps all three targets behaviorally identical.
//
//   component C        -> functions  void C_attach(void)
//   prop(p)            -> an nsv literal, inlined
//   let x = e          -> nsv x = e;
//   print(e)           -> nsv_print(e)
//   call C.f()         -> C_f()
//   threads: N         -> pthread_create x N, joined
// ===========================================================================
#include "emitters.h"

#include <sstream>
#include <string>

namespace nordshrift {
namespace {

std::string sanitize(const std::string& name) {
    std::string out;
    for (char c : name) out += (c == '-') ? '_' : c;
    return out;
}

std::string escapeC(const std::string& s) {
    std::string o;
    for (char c : s) {
        switch (c) {
            case '"': o += "\\\""; break;
            case '\\': o += "\\\\"; break;
            case '\n': o += "\\n"; break;
            case '\t': o += "\\t"; break;
            case '\r': o += "\\r"; break;
            default: o += c;
        }
    }
    return o;
}

// The runtime prelude: the tagged value type and its operations.
const char* kPrelude = R"PRE(/* Generated by Nordshrift (C target) */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

typedef enum { NSV_INT, NSV_DBL, NSV_BOOL, NSV_STR } nsv_tag;
typedef struct { nsv_tag t; long long i; double d; int b; char* s; } nsv;

static nsv nsv_int(long long v){ nsv x; x.t=NSV_INT; x.i=v; return x; }
static nsv nsv_dbl(double v){ nsv x; x.t=NSV_DBL; x.d=v; return x; }
static nsv nsv_bool(int v){ nsv x; x.t=NSV_BOOL; x.b=v?1:0; return x; }
static nsv nsv_str(const char* v){ nsv x; x.t=NSV_STR; x.s=strdup(v); return x; }

static double nsv_num(nsv v){
    switch(v.t){ case NSV_INT: return (double)v.i; case NSV_DBL: return v.d;
                 case NSV_BOOL: return v.b; default: return 0; }
}
static int nsv_truth(nsv v){
    switch(v.t){ case NSV_INT: return v.i!=0; case NSV_DBL: return v.d!=0;
                 case NSV_BOOL: return v.b; case NSV_STR: return 1; } return 0;
}
static void nsv_render(nsv v, char* buf, size_t n){
    switch(v.t){
        case NSV_INT:  snprintf(buf,n,"%lld",v.i); break;
        case NSV_DBL:  snprintf(buf,n,"%g",v.d); break;
        case NSV_BOOL: snprintf(buf,n,"%s",v.b?"true":"false"); break;
        case NSV_STR:  snprintf(buf,n,"%s",v.s?v.s:""); break;
    }
}
static nsv nsv_add(nsv a, nsv b){
    if(a.t==NSV_STR || b.t==NSV_STR){
        char sa[256], sb[256], out[512];
        nsv_render(a,sa,sizeof sa); nsv_render(b,sb,sizeof sb);
        snprintf(out,sizeof out,"%s%s",sa,sb); return nsv_str(out);
    }
    if(a.t==NSV_INT && b.t==NSV_INT) return nsv_int(a.i+b.i);
    return nsv_dbl(nsv_num(a)+nsv_num(b));
}
static nsv nsv_sub(nsv a, nsv b){ if(a.t==NSV_INT&&b.t==NSV_INT) return nsv_int(a.i-b.i); return nsv_dbl(nsv_num(a)-nsv_num(b)); }
static nsv nsv_mul(nsv a, nsv b){ if(a.t==NSV_INT&&b.t==NSV_INT) return nsv_int(a.i*b.i); return nsv_dbl(nsv_num(a)*nsv_num(b)); }
static nsv nsv_div(nsv a, nsv b){ if(a.t==NSV_INT&&b.t==NSV_INT) return nsv_int(a.i/b.i); return nsv_dbl(nsv_num(a)/nsv_num(b)); }
static nsv nsv_mod(nsv a, nsv b){ return nsv_int(a.i % b.i); }
static nsv nsv_neg(nsv a){ if(a.t==NSV_INT) return nsv_int(-a.i); return nsv_dbl(-nsv_num(a)); }
static nsv nsv_lt(nsv a, nsv b){ return nsv_bool(nsv_num(a)<nsv_num(b)); }
static nsv nsv_le(nsv a, nsv b){ return nsv_bool(nsv_num(a)<=nsv_num(b)); }
static nsv nsv_gt(nsv a, nsv b){ return nsv_bool(nsv_num(a)>nsv_num(b)); }
static nsv nsv_ge(nsv a, nsv b){ return nsv_bool(nsv_num(a)>=nsv_num(b)); }
static nsv nsv_eq(nsv a, nsv b){
    if(a.t==NSV_STR&&b.t==NSV_STR) return nsv_bool(strcmp(a.s,b.s)==0);
    return nsv_bool(nsv_num(a)==nsv_num(b));
}
static nsv nsv_ne(nsv a, nsv b){ nsv e=nsv_eq(a,b); return nsv_bool(!e.b); }
static nsv nsv_and(nsv a, nsv b){ return nsv_bool(nsv_truth(a)&&nsv_truth(b)); }
static nsv nsv_or(nsv a, nsv b){ return nsv_bool(nsv_truth(a)||nsv_truth(b)); }
static nsv nsv_not(nsv a){ return nsv_bool(!nsv_truth(a)); }
static void nsv_print(nsv v){ char buf[512]; nsv_render(v,buf,sizeof buf); printf("%s\n", buf); }
)PRE";

struct CEmitter {
    const Sheet& sheet;
    const Component* self = nullptr;
    std::ostringstream out;

    explicit CEmitter(const Sheet& s) : sheet(s) {}

    std::string run() {
        out << kPrelude << "\n";

        // forward declarations for all attaches
        for (auto& c : sheet.components)
            for (auto& a : c.attaches)
                out << "static void " << c.name << "_" << sanitize(a.name) << "(void);\n";
        out << "\n";

        for (auto& c : sheet.components) emitComponent(c);

        emitThreadWrappers();
        emitMain();
        return out.str();
    }

    void indent(int n) { for (int i = 0; i < n; i++) out << "    "; }

    void emitComponent(const Component& c) {
        out << "/* ---- component " << c.name << " ---- */\n";
        for (auto& a : c.attaches) {
            self = &c;
            out << "static void " << c.name << "_" << sanitize(a.name) << "(void) {\n";
            emitBlock(*a.body, 1);
            out << "}\n\n";
            self = nullptr;
        }
    }

    void emitBlock(const Block& b, int ind) { for (auto& s : b.stmts) emitStmt(s.get(), ind); }

    void emitStmt(const Stmt* s, int ind) {
        if (auto b = dynamic_cast<const Block*>(s)) { indent(ind); out << "{\n"; emitBlock(*b, ind+1); indent(ind); out << "}\n"; return; }
        if (auto l = dynamic_cast<const LetStmt*>(s)) { indent(ind); out << "nsv " << l->name << " = "; emitExpr(l->init.get()); out << ";\n"; return; }
        if (auto a = dynamic_cast<const AssignStmt*>(s)) { indent(ind); out << a->name << " = "; emitExpr(a->value.get()); out << ";\n"; return; }
        if (auto p = dynamic_cast<const PrintStmt*>(s)) { indent(ind); out << "nsv_print("; emitExpr(p->expr.get()); out << ");\n"; return; }
        if (auto i = dynamic_cast<const IfStmt*>(s)) {
            indent(ind); out << "if (nsv_truth("; emitExpr(i->cond.get()); out << ")) {\n";
            emitStmt(i->thenS.get(), ind+1);
            indent(ind); out << "}";
            if (i->elseS) { out << " else {\n"; emitStmt(i->elseS.get(), ind+1); indent(ind); out << "}"; }
            out << "\n"; return;
        }
        if (auto w = dynamic_cast<const WhileStmt*>(s)) {
            indent(ind); out << "while (nsv_truth("; emitExpr(w->cond.get()); out << ")) {\n";
            emitStmt(w->body.get(), ind+1);
            indent(ind); out << "}\n"; return;
        }
        if (auto c = dynamic_cast<const CallStmt*>(s)) { indent(ind); out << c->comp << "_" << sanitize(c->attach) << "();\n"; return; }
    }

    void emitExpr(const Expr* e) {
        if (auto n = dynamic_cast<const NumLit*>(e)) {
            if (n->isInt) out << "nsv_int(" << (long long)n->value << ")";
            else out << "nsv_dbl(" << n->value << ")";
            return;
        }
        if (auto s = dynamic_cast<const StrLit*>(e)) { out << "nsv_str(\"" << escapeC(s->value) << "\")"; return; }
        if (auto b = dynamic_cast<const BoolLit*>(e)) { out << "nsv_bool(" << (b->value?1:0) << ")"; return; }
        if (auto v = dynamic_cast<const VarRef*>(e)) { out << v->name; return; }
        if (auto p = dynamic_cast<const PropRef*>(e)) { emitProp(p->name); return; }
        if (auto u = dynamic_cast<const Unary*>(e)) {
            out << (u->op == "-" ? "nsv_neg(" : "nsv_not("); emitExpr(u->e.get()); out << ")"; return;
        }
        if (auto bi = dynamic_cast<const Binary*>(e)) {
            const std::string& o = bi->op;
            std::string fn = o=="+"?"nsv_add":o=="-"?"nsv_sub":o=="*"?"nsv_mul":o=="/"?"nsv_div":
                             o=="%"?"nsv_mod":o=="=="?"nsv_eq":o=="!="?"nsv_ne":o=="<"?"nsv_lt":
                             o=="<="?"nsv_le":o==">"?"nsv_gt":o==">="?"nsv_ge":o=="&&"?"nsv_and":"nsv_or";
            out << fn << "("; emitExpr(bi->l.get()); out << ", "; emitExpr(bi->r.get()); out << ")"; return;
        }
    }

    void emitProp(const std::string& name) {
        if (!self) { out << "nsv_int(0)"; return; }
        auto it = self->props.find(name);
        if (it == self->props.end()) { out << "nsv_str(\"\")"; return; }
        const PropValue& v = it->second;
        switch (v.kind) {
            case ValKind::Number: if (v.isInt) out << "nsv_int(" << (long long)v.num << ")"; else out << "nsv_dbl(" << v.num << ")"; break;
            case ValKind::Str:    out << "nsv_str(\"" << escapeC(v.s) << "\")"; break;
            case ValKind::Bool:   out << "nsv_bool(" << (v.b?1:0) << ")"; break;
            case ValKind::Ident:  out << "nsv_str(\"" << escapeC(v.s) << "\")"; break;
        }
    }

    // A thread wrapper runs a component's activation body once (on-start + ticks).
    void emitThreadWrappers() {
        for (auto& c : sheet.components) {
            if (c.threads() <= 1) continue;
            if (!c.findAttach("on-start") && !c.findAttach("tick")) continue;
            out << "static void* _worker_" << c.name << "(void* _a) {\n";
            out << "    (void)_a;\n";
            if (c.findAttach("on-start")) out << "    " << c.name << "_" << sanitize("on-start") << "();\n";
            if (c.findAttach("tick"))
                out << "    for (long long _t=0; _t<" << c.repeat() << "; _t++) "
                    << c.name << "_" << sanitize("tick") << "();\n";
            out << "    return NULL;\n}\n\n";
        }
    }

    void emitActivation(const Component& c, int ind) {
        bool hasStart = c.findAttach("on-start");
        bool hasTick  = c.findAttach("tick");
        if (!hasStart && !hasTick) return;
        long long th = c.threads();

        indent(ind); out << "/* activate " << c.name;
        if (th > 1) out << " on " << th << " pthread(s)";
        out << " */\n";

        if (th > 1) {
            indent(ind); out << "{\n";
            indent(ind+1); out << "pthread_t _th[" << th << "];\n";
            indent(ind+1); out << "for (int _w=0; _w<" << th << "; _w++) pthread_create(&_th[_w], NULL, _worker_" << c.name << ", NULL);\n";
            indent(ind+1); out << "for (int _w=0; _w<" << th << "; _w++) pthread_join(_th[_w], NULL);\n";
            indent(ind); out << "}\n";
        } else {
            if (hasStart) { indent(ind); out << c.name << "_" << sanitize("on-start") << "();\n"; }
            if (hasTick) {
                indent(ind); out << "for (long long _t=0; _t<" << c.repeat() << "; _t++) "
                                 << c.name << "_" << sanitize("tick") << "();\n";
            }
        }
    }

    void emitMain() {
        out << "int main(void) {\n";
        for (int idx : sheet.order) emitActivation(sheet.components[idx], 1);
        const Component* mc = sheet.mainComponent();
        if (mc) { indent(1); out << mc->name << "_main();\n"; }
        out << "    return 0;\n}\n";
    }
};

} // namespace

std::string emitC(const Sheet& sheet) {
    CEmitter e(sheet);
    return e.run();
}

} // namespace nordshrift
