// ===========================================================================
// emit_sleela.cpp  --  Nordshrift component graph -> .sleela source.
//
// The emitted Sleela runs on the Sleela C core (../core). Everything is placed
// in one class `NordshriftProgram`; each attach becomes a method named
// `Comp_attach`. The Sleela compiler ignores declared types (they are checked
// only syntactically), so untyped attach `let` bindings are emitted as typed
// locals with a nominal `int`/`String` annotation while still holding whatever
// dynamic value the core computes.
//
// Threads: the current core is single-threaded, so `threads: N` is emitted as N
// sequential activation passes -- same observable output, honoring component
// isolation. (Becomes a real fan-out when the core gains threads.)
// ===========================================================================
#include "emitters.h"

#include <sstream>
#include <string>

namespace nordshrift {
namespace {

std::string sanitize(const std::string& name) {
    std::string out;
    for (char c : name) out += (c == '-') ? '_' : c;
    return out;
}

std::string escapeSleela(const std::string& s) {
    std::string o;
    for (char c : s) {
        switch (c) {
            case '"': o += "\\\""; break;
            case '\\': o += "\\\\"; break;
            case '\n': o += "\\n"; break;
            case '\t': o += "\\t"; break;
            case '\r': o += "\\r"; break;
            default: o += c;
        }
    }
    return o;
}

struct SleelaEmitter {
    const Sheet& sheet;
    const Component* self = nullptr;
    std::ostringstream out;

    explicit SleelaEmitter(const Sheet& s) : sheet(s) {}

    std::string run() {
        out << "// Generated by Nordshrift (Sleela target) -- runs on the C core.\n";
        out << "class NordshriftProgram {\n\n";

        for (auto& c : sheet.components)
            for (auto& a : c.attaches) emitAttach(c, a);

        // For threaded components, emit a 0-arg worker method that performs one
        // activation pass (on-start + ticks). main() spawns N of these.
        for (auto& c : sheet.components) emitWorkerIfThreaded(c);

        emitMain();

        out << "}\n";
        return out.str();
    }

    void indent(int n) { for (int i = 0; i < n; i++) out << "    "; }

    void emitAttach(const Component& c, const Attach& a) {
        self = &c;
        indent(1);
        out << "void " << c.name << "_" << sanitize(a.name) << "() {\n";
        emitBlock(*a.body, 2);
        indent(1); out << "}\n\n";
        self = nullptr;
    }

    void emitBlock(const Block& b, int ind) { for (auto& s : b.stmts) emitStmt(s.get(), ind); }

    void emitStmt(const Stmt* s, int ind) {
        if (auto b = dynamic_cast<const Block*>(s)) { indent(ind); out << "{\n"; emitBlock(*b, ind+1); indent(ind); out << "}\n"; return; }
        if (auto l = dynamic_cast<const LetStmt*>(s)) {
            // Sleela requires a type token; the core ignores it, so `int` is safe
            // as a nominal annotation regardless of the runtime value.
            indent(ind); out << "int " << l->name << " = "; emitExpr(l->init.get()); out << ";\n"; return;
        }
        if (auto a = dynamic_cast<const AssignStmt*>(s)) { indent(ind); out << a->name << " = "; emitExpr(a->value.get()); out << ";\n"; return; }
        if (auto p = dynamic_cast<const PrintStmt*>(s)) { indent(ind); out << "print("; emitExpr(p->expr.get()); out << ");\n"; return; }
        if (auto i = dynamic_cast<const IfStmt*>(s)) {
            indent(ind); out << "if ("; emitExpr(i->cond.get()); out << ") {\n";
            emitStmt(i->thenS.get(), ind+1);
            indent(ind); out << "}";
            if (i->elseS) { out << " else {\n"; emitStmt(i->elseS.get(), ind+1); indent(ind); out << "}"; }
            out << "\n"; return;
        }
        if (auto w = dynamic_cast<const WhileStmt*>(s)) {
            indent(ind); out << "while ("; emitExpr(w->cond.get()); out << ") {\n";
            emitStmt(w->body.get(), ind+1);
            indent(ind); out << "}\n"; return;
        }
        if (auto c = dynamic_cast<const CallStmt*>(s)) { indent(ind); out << c->comp << "_" << sanitize(c->attach) << "();\n"; return; }
    }

    void emitExpr(const Expr* e) {
        if (auto n = dynamic_cast<const NumLit*>(e)) {
            if (n->isInt) out << (long long)n->value; else out << n->value;
            return;
        }
        if (auto s = dynamic_cast<const StrLit*>(e)) { out << "\"" << escapeSleela(s->value) << "\""; return; }
        if (auto b = dynamic_cast<const BoolLit*>(e)) { out << (b->value ? "true" : "false"); return; }
        if (auto v = dynamic_cast<const VarRef*>(e)) { out << v->name; return; }
        if (auto p = dynamic_cast<const PropRef*>(e)) { emitProp(p->name); return; }
        if (auto u = dynamic_cast<const Unary*>(e)) { out << u->op << "("; emitExpr(u->e.get()); out << ")"; return; }
        if (auto bi = dynamic_cast<const Binary*>(e)) {
            out << "("; emitExpr(bi->l.get()); out << " " << bi->op << " "; emitExpr(bi->r.get()); out << ")"; return;
        }
    }

    void emitProp(const std::string& name) {
        if (!self) { out << "0"; return; }
        auto it = self->props.find(name);
        if (it == self->props.end()) { out << "\"\""; return; }
        const PropValue& v = it->second;
        switch (v.kind) {
            case ValKind::Number: if (v.isInt) out << (long long)v.num; else out << v.num; break;
            case ValKind::Str:    out << "\"" << escapeSleela(v.s) << "\""; break;
            case ValKind::Bool:   out << (v.b ? "true" : "false"); break;
            case ValKind::Ident:  out << "\"" << escapeSleela(v.s) << "\""; break;
        }
    }

    // Emit the body of one activation pass (on-start once, then tick x repeat).
    void emitPassBody(const Component& c, int ind) {
        if (c.findAttach("on-start")) { indent(ind); out << c.name << "_" << sanitize("on-start") << "();\n"; }
        if (c.findAttach("tick")) {
            indent(ind); out << "for (int _t = 0; _t < " << c.repeat() << "; _t = _t + 1) {\n";
            indent(ind+1); out << c.name << "_" << sanitize("tick") << "();\n";
            indent(ind); out << "}\n";
        }
    }

    // A threaded component gets a 0-arg worker method that runs one pass, so
    // main() can spawn N of them onto real threads.
    void emitWorkerIfThreaded(const Component& c) {
        if (c.threads() <= 1) return;
        if (!c.findAttach("on-start") && !c.findAttach("tick")) return;
        self = &c;
        indent(1); out << "void " << c.name << "_activate() {\n";
        emitPassBody(c, 2);
        indent(1); out << "}\n\n";
        self = nullptr;
    }

    void emitActivation(const Component& c, int ind) {
        bool hasStart = c.findAttach("on-start");
        bool hasTick  = c.findAttach("tick");
        if (!hasStart && !hasTick) return;
        long long th = c.threads();

        if (th <= 1) {
            indent(ind); out << "// activate " << c.name << "\n";
            emitPassBody(c, ind);
            return;
        }

        // threads: N  ->  spawn N real worker threads, then join.
        indent(ind); out << "// activate " << c.name << " on " << th << " real thread(s)\n";
        indent(ind); out << "{\n";
        indent(ind+1); out << "int _n = 0;\n";
        indent(ind+1); out << "while (_n < " << th << ") {\n";
        indent(ind+2); out << "spawn(" << c.name << "_activate);\n";
        indent(ind+2); out << "_n = _n + 1;\n";
        indent(ind+1); out << "}\n";
        indent(ind+1); out << "join();\n";
        indent(ind); out << "}\n";
    }

    void emitMain() {
        indent(1); out << "void main() {\n";
        for (int idx : sheet.order) emitActivation(sheet.components[idx], 2);
        const Component* mc = sheet.mainComponent();
        if (mc) { indent(2); out << mc->name << "_main();\n"; }
        indent(1); out << "}\n";
    }
};

} // namespace

std::string emitSleela(const Sheet& sheet) {
    SleelaEmitter e(sheet);
    return e.run();
}

} // namespace nordshrift
